json.additional.classes=
json.ignore.responses=dev.resteasy.examples.service.Library#getBook,dev.resteasy.examples.resources.FileResource#dir
# This option has been used for bean-validation attempt, jaxrs-jwt
#json.ignore.responses=dev.resteasy.examples.service.Library#getBook,dev.resteasy.examples.resources.FileResource#dir,org.jboss.quickstarts.jaxrsjwt.rs.AuthResource#demonstrateClaims,org.jboss.quickstarts.jaxrsjwt.rs.AuthResource#postJWT
# This option has been used for bean-validation attempt, jaxrs-jwt
# excluded.dependencies=nimbus-jose-.*
# This option has been used for bean-validation attempt, jaxrs-jwt
# preloaded.resources=META-INF/validation.xml,META-INF/constraint-mapping.xml