native-image -jar module-launcher/target/ModuleLauncher-1.0-SNAPSHOT.jar \
-Djboss.home.dir=/Users/jdenise/workspaces/wildfly-graal/min-server2 \
-Dorg.jboss.boot.log.file=/Users/jdenise/workspaces/wildfly-graal/min-server2/standalone/log/server.log \
-Dlogging.configuration=file:///Users/jdenise/workspaces/graal/wildfly-graal/min-server2/standalone/standalone/logging.properties \
-Duser.home==/Users/jdenise \
-Djboss.server.base.dir=/Users/jdenise/workspaces/wildfly-graal/min-server2/standalone \
-cp /Users/jdenise/.m2/repository/org/jboss/modules/jboss-modules/2.3.0.Final-SNAPSHOT/jboss-modules-2.3.0.Final-SNAPSHOT.jar:\
./min-server2/modules/system/layers/base/internal/javax/json/api/ee8/main/jakarta.json-1.1.6.jar:\
./min-server2/modules/system/layers/base/io/smallrye/common/constraint/main/smallrye-common-constraint-2.13.9.jar:\
./min-server2/modules/system/layers/base/io/smallrye/common/cpu/main/smallrye-common-cpu-2.13.9.jar:\
./min-server2/modules/system/layers/base/io/smallrye/common/expression/main/smallrye-common-expression-2.13.9.jar:\
./min-server2/modules/system/layers/base/io/smallrye/common/function/main/smallrye-common-function-2.13.9.jar:\
./min-server2/modules/system/layers/base/io/smallrye/common/net/main/smallrye-common-net-2.13.9.jar:\
./min-server2/modules/system/layers/base/io/smallrye/common/os/main/smallrye-common-os-2.13.9.jar:\
./min-server2/modules/system/layers/base/io/smallrye/jandex/main/jandex-3.5.0.jar:\
./min-server2/modules/system/layers/base/io/undertow/core/main/undertow-core-2.3.20.Final.jar:\
./min-server2/modules/system/layers/base/jakarta/interceptor/api/main/jakarta.interceptor-api-2.1.0.jar:\
./min-server2/modules/system/layers/base/jakarta/json/api/main/jakarta.json-api-2.1.3.jar:\
./min-server2/modules/system/layers/base/jakarta/security/auth/message/api/main/jakarta.authentication-api-3.0.0.jar:\
./min-server2/modules/system/layers/base/org/aesh/main/aesh-2.4.jar:\
./min-server2/modules/system/layers/base/org/aesh/main/aesh-extensions-1.8.jar:\
./min-server2/modules/system/layers/base/org/aesh/main/readline-2.2.jar:\
./min-server2/modules/system/layers/base/org/apache/sshd/main/sshd-common-2.16.0.jar:\
./min-server2/modules/system/layers/base/org/apache/sshd/main/sshd-core-2.16.0.jar:\
./min-server2/modules/system/layers/base/org/bouncycastle/bcpg/main/bcpg-jdk18on-1.82.jar:\
./min-server2/modules/system/layers/base/org/bouncycastle/bcpkix/main/bcpkix-jdk18on-1.82.jar:\
./min-server2/modules/system/layers/base/org/bouncycastle/bcprov/main/bcprov-jdk18on-1.82.jar:\
./min-server2/modules/system/layers/base/org/bouncycastle/bcutil/main/bcutil-jdk18on-1.82.jar:\
./min-server2/modules/system/layers/base/org/eclipse/parsson/main/parsson-1.1.7.jar:\
./min-server2/modules/system/layers/base/org/fusesource/jansi/main/jansi-1.18.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/cli/main/wildfly-cli-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/controller-client/main/wildfly-controller-client-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/controller/main/wildfly-controller-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/core-security/main/wildfly-core-security-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/deployment-repository/main/wildfly-deployment-repository-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/domain-http-interface/main/wildfly-domain-http-interface-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/domain-management/main/wildfly-domain-management-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/host-controller/main/wildfly-host-controller-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/jmx/main/wildfly-jmx-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/management-client-content/main/wildfly-management-client-content-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/network/main/wildfly-network-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/platform-mbean/main/wildfly-platform-mbean-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/process-controller/main/wildfly-process-controller-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/protocol/main/wildfly-protocol-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/remoting/main/wildfly-remoting-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/server/main/wildfly-server-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/as/version/main/wildfly-version-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/classfilewriter/main/jboss-classfilewriter-1.3.1.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/dmr/main/jboss-dmr-1.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/invocation/main/jboss-invocation-2.0.1.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/logging/main/jboss-logging-3.6.1.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.1.19.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/marshalling/main/jboss-marshalling-2.2.3.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/marshalling/river/main/jboss-marshalling-river-2.2.3.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/msc/main/jboss-msc-1.5.6.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/remoting/main/jboss-remoting-5.0.31.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/staxmapper/main/staxmapper-1.5.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/stdio/main/jboss-stdio-1.1.0.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/threads/main/jboss-threads-3.9.1.jar:\
./min-server2/modules/system/layers/base/org/jboss/vfs/main/jboss-vfs-3.3.2.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/xnio/main/xnio-api-3.8.16.Final.jar:\
./min-server2/modules/system/layers/base/org/jboss/xnio/nio/main/xnio-nio-3.8.16.Final.jar:\
./min-server2/modules/system/layers/base/org/projectodd/vdx/main/vdx-core-1.1.6.jar:\
./min-server2/modules/system/layers/base/org/projectodd/vdx/main/vdx-wildfly-1.1.6.jar:\
./min-server2/modules/system/layers/base/org/slf4j/impl/main/slf4j-jboss-logmanager-2.0.1.Final.jar:\
./min-server2/modules/system/layers/base/org/slf4j/main/slf4j-api-2.0.17.jar:\
./min-server2/modules/system/layers/base/org/wildfly/bootable-jar/main/wildfly-jar-runtime-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/client/config/main/wildfly-client-config-1.0.1.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/common/main/wildfly-common-2.0.1.jar:\
./min-server2/modules/system/layers/base/org/wildfly/embedded/main/wildfly-embedded-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/extension/core-management-client/main/wildfly-core-management-client-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/installation-manager/api/main/installation-manager-api-1.1.1.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/installation-manager/main/wildfly-installation-manager-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/io/spi/main/wildfly-io-spi-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-asn1-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-audit-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-auth-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-auth-server-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-auth-server-deprecated-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-auth-server-http-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-auth-server-sasl-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-auth-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-base-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-client-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-credential-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-credential-source-impl-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-credential-store-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-digest-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-encryption-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-basic-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-bearer-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-cert-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-digest-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-external-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-form-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-spnego-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-sso-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-http-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-json-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-keystore-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-mechanism-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-mechanism-digest-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-mechanism-gssapi-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-mechanism-http-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-mechanism-oauth2-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-mechanism-scram-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-password-impl-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-permission-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-provider-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-realm-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-realm-jdbc-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-realm-ldap-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-realm-token-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-anonymous-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-auth-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-digest-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-entity-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-external-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-gs2-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-gssapi-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-localuser-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-oauth2-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-otp-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-plain-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-sasl-scram-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-security-manager-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-security-manager-action-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-ssh-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-ssl-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-x500-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-x500-cert-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-x500-cert-acme-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-x500-cert-util-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-base/main/wildfly-elytron-x500-principal-2.7.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/elytron-web/undertow-server/main/undertow-server-4.1.2.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/jakarta/authentication/main/jakarta-authentication-3.2.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/jakarta-authorization-3.2.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/service/main/wildfly-service-30.0.0.Final.jar:\
./min-server2/modules/system/layers/base/org/wildfly/unstable/annotation/api/indexer/main/unstable-api-annotation-classpath-indexer-1.0.2.Final.jar:\
./min-server2/modules/system/layers/base/org/yaml/snakeyaml/main/snakeyaml-2.4.jar \
--initialize-at-build-time=launcher.Launcher,org.slf4j.helpers.NOPLogger,org.wildfly.common._private,org.jboss.logmanager,\
org.jboss.modules,org.apache.sshd.common.file.root.RootedFileSystemProvider,org.slf4j.impl.Slf4jLogger \
--enable-url-protocols=jar \
-H:ConfigurationFileDirectories=min-server-graal-agent2

echo "Image Built"