current_dir=$(pwd)

IFS=$'\n'
array=($(find ./min-core-server/modules/system/layers/base/ -name \*.jar))
unset IFS

arraylength=${#array[@]}

cmd="
native-image -jar module-launcher/target/ModuleLauncher-1.0-SNAPSHOT.jar \
wildfly-launcher \
-Dorg.wildfly.graal.deployment.module=deployment.helloworld.war \
-Dorg.jboss.modules.record.classes=pre.compiled.jsps,org.jboss.as.quickstarts.helloworld,org.jboss.quickstarts.websocket,org.jboss.as.quickstarts.websocket_hello,org.jboss.as.quickstart.http_custom_mechanism \
-Djboss.home.dir=${current_dir}/min-core-server \
-Dlogging.configuration=file://${current_dir}/min-core-server/standalone/configuration/logging.properties \
-Dorg.jboss.boot.log.file=${current_dir}/min-core-server/standalone/log/server.log \
-Duser.home==/Users/foo \
-Djboss.server.base.dir=${current_dir}/min-core-server/standalone \
-H:+PrintClassInitialization \
--initialize-at-build-time=\
ORG.FOO.DEPLOYMENT.CLASSES,\
org.jboss.as.quickstart.http_custom_mechanism.CustomMechanismFactory,\
ORG.FOO.CLASSES.NEEDED.BY.ALL.SERVICES,\
org.slf4j.impl.Slf4jLogger,\
org.slf4j.spi.LocationAwareLogger,\
org.slf4j.spi,\
org.slf4j,\
java.io.Serializable,\
org.xnio.sasl,\
org.jboss.as.remoting,\
org.jboss.as.remoting.RemotingSubsystemTransformationDescriptionFactory,\
org.wildfly.extension.elytron,\
org.jboss.msc.service.ServiceController\\\$Mode,\
sun.security.jgss.GSSManagerImpl,\
io.undertow.client.http2,\
io.undertow.websockets.jsr,\
org.jboss.marshalling.river,\
io.undertow.servlet.util,\
org.jboss.marshalling.reflect,\
org.jboss.marshalling,\
org.eclipse.jgit.transport.sshd,\
ORG.FOO.CLASSES.DUMPED.BY.SERVICES.DISCOVERY,\
io.undertow.attribute.AuthenticationTypeExchangeAttribute\\\$Builder,\
io.undertow.attribute.BytesSentAttribute\\\$Builder,\
io.undertow.attribute.CookieAttribute\\\$Builder,\
io.undertow.attribute.DateTimeAttribute\\\$Builder,\
io.undertow.attribute.ExchangeAttributeBuilder,\
io.undertow.attribute.HostAndPortAttribute\\\$Builder,\
io.undertow.attribute.IdentUsernameAttribute\\\$Builder,\
io.undertow.attribute.LocalIPAttribute\\\$Builder,\
io.undertow.attribute.LocalPortAttribute\\\$Builder,\
io.undertow.attribute.LocalServerNameAttribute\\\$Builder,\
io.undertow.attribute.NullAttribute\\\$Builder,\
io.undertow.attribute.PathParameterAttribute\\\$Builder,\
io.undertow.attribute.PredicateContextAttribute\\\$Builder,\
io.undertow.attribute.QueryParameterAttribute\\\$Builder,\
io.undertow.attribute.QueryStringAttribute\\\$Builder,\
io.undertow.attribute.RelativePathAttribute\\\$Builder,\
io.undertow.attribute.RemoteHostAttribute\\\$Builder,\
io.undertow.attribute.RemoteIPAttribute\\\$Builder,\
io.undertow.attribute.RemoteObfuscatedIPAttribute\\\$Builder,\
io.undertow.attribute.RemoteUserAttribute\\\$Builder,\
io.undertow.attribute.RequestCookieAttribute\\\$Builder,\
io.undertow.attribute.RequestHeaderAttribute\\\$Builder,\
io.undertow.attribute.RequestLineAttribute\\\$Builder,\
io.undertow.attribute.RequestMethodAttribute\\\$Builder,\
io.undertow.attribute.RequestPathAttribute\\\$Builder,\
io.undertow.attribute.RequestProtocolAttribute\\\$Builder,\
io.undertow.attribute.RequestSchemeAttribute\\\$Builder,\
io.undertow.attribute.RequestURLAttribute\\\$Builder,\
io.undertow.attribute.ResolvedPathAttribute\\\$Builder,\
io.undertow.attribute.ResponseCodeAttribute\\\$Builder,\
io.undertow.attribute.ResponseCookieAttribute\\\$Builder,\
io.undertow.attribute.ResponseHeaderAttribute\\\$Builder,\
io.undertow.attribute.ResponseReasonPhraseAttribute\\\$Builder,\
io.undertow.attribute.ResponseTimeAttribute\\\$Builder,\
io.undertow.attribute.SecureExchangeAttribute\\\$Builder,\
io.undertow.attribute.SslCipherAttribute\\\$Builder,\
io.undertow.attribute.SslClientCertAttribute\\\$Builder,\
io.undertow.attribute.SslSessionIdAttribute\\\$Builder,\
io.undertow.attribute.StoredResponse\\\$Builder,\
io.undertow.attribute.ThreadNameAttribute\\\$Builder,\
io.undertow.attribute.TransportProtocolAttribute\\\$Builder,\
io.undertow.client.ClientProvider,\
io.undertow.client.ajp.AjpClientProvider,\
io.undertow.client.http.HttpClientProvider,\
io.undertow.client.http2.Http2ClearClientProvider,\
io.undertow.client.http2.Http2ClientProvider,\
io.undertow.client.http2.Http2PriorKnowledgeClientProvider,\
io.undertow.predicate.AuthenticationRequiredPredicate\\\$Builder,\
io.undertow.predicate.ContainsPredicate\\\$Builder,\
io.undertow.predicate.EqualsPredicate\\\$Builder,\
io.undertow.predicate.ExistsPredicate\\\$Builder,\
io.undertow.predicate.IdempotentPredicate\\\$Builder,\
io.undertow.predicate.MaxContentSizePredicate\\\$Builder,\
io.undertow.predicate.MethodPredicate\\\$Builder,\
io.undertow.predicate.MinContentSizePredicate\\\$Builder,\
io.undertow.predicate.PathMatchPredicate\\\$Builder,\
io.undertow.predicate.PathPrefixPredicate\\\$Builder,\
io.undertow.predicate.PathSuffixPredicate\\\$Builder,\
io.undertow.predicate.PathTemplatePredicate\\\$Builder,\
io.undertow.predicate.PredicateBuilder,\
io.undertow.predicate.PredicatesHandler\\\$DoneHandlerBuilder,\
io.undertow.predicate.PredicatesHandler\\\$RestartHandlerBuilder,\
io.undertow.predicate.RegularExpressionPredicate\\\$Builder,\
io.undertow.predicate.RequestLargerThanPredicate\\\$Builder,\
io.undertow.predicate.RequestSmallerThanPredicate\\\$Builder,\
io.undertow.predicate.SecurePredicate\\\$Builder,\
io.undertow.protocols.alpn.ALPNEngineManager,\
io.undertow.protocols.alpn.ALPNProvider,\
io.undertow.protocols.alpn.DefaultAlpnEngineManager,\
io.undertow.protocols.alpn.ModularJdkAlpnProvider,\
io.undertow.protocols.alpn.OpenSSLAlpnProvider,\
io.undertow.protocols.ssl.SNIAlpnEngineManager,\
io.undertow.server.JvmRouteHandler\\\$Builder,\
io.undertow.server.handlers.AccessControlListHandler\\\$Builder,\
io.undertow.server.handlers.ActiveRequestTrackerHandler\\\$Builder,\
io.undertow.server.handlers.AllowedMethodsHandler\\\$Builder,\
io.undertow.server.handlers.BlockingHandler\\\$Builder,\
io.undertow.server.handlers.ByteRangeHandler\\\$Builder,\
io.undertow.server.handlers.CanonicalPathHandler\\\$Builder,\
io.undertow.server.handlers.DisableCacheHandler\\\$Builder,\
io.undertow.server.handlers.DisallowedMethodsHandler\\\$Builder,\
io.undertow.server.handlers.ForwardedHandler\\\$Builder,\
io.undertow.server.handlers.HttpContinueAcceptingHandler\\\$Builder,\
io.undertow.server.handlers.HttpTraceHandler\\\$Builder,\
io.undertow.server.handlers.IPAddressAccessControlHandler\\\$Builder,\
io.undertow.server.handlers.JDBCLogHandler\\\$Builder,\
io.undertow.server.handlers.LearningPushHandler\\\$Builder,\
io.undertow.server.handlers.LocalNameResolvingHandler\\\$Builder,\
io.undertow.server.handlers.PathSeparatorHandler\\\$Builder,\
io.undertow.server.handlers.PeerNameResolvingHandler\\\$Builder,\
io.undertow.server.handlers.ProxyPeerAddressHandler\\\$Builder,\
io.undertow.server.handlers.RedirectHandler\\\$Builder,\
io.undertow.server.handlers.RequestBufferingHandler\\\$Builder,\
io.undertow.server.handlers.RequestDumpingHandler\\\$Builder,\
io.undertow.server.handlers.RequestLimitingHandler\\\$Builder,\
io.undertow.server.handlers.ResponseRateLimitingHandler\\\$Builder,\
io.undertow.server.handlers.SSLHeaderHandler\\\$Builder,\
io.undertow.server.handlers.SameSiteCookieHandler\\\$Builder,\
io.undertow.server.handlers.SecureCookieHandler\\\$Builder,\
io.undertow.server.handlers.SetAttributeHandler\\\$Builder,\
io.undertow.server.handlers.SetAttributeHandler\\\$ClearBuilder,\
io.undertow.server.handlers.SetErrorHandler\\\$Builder,\
io.undertow.server.handlers.SetHeaderHandler\\\$Builder,\
io.undertow.server.handlers.StoredResponseHandler\\\$Builder,\
io.undertow.server.handlers.StuckThreadDetectionHandler\\\$Builder,\
io.undertow.server.handlers.URLDecodingHandler\\\$Builder,\
io.undertow.server.handlers.accesslog.AccessLogHandler\\\$Builder,\
io.undertow.server.handlers.builder.HandlerBuilder,\
io.undertow.server.handlers.builder.ResponseCodeHandlerBuilder,\
io.undertow.server.handlers.builder.RewriteHandlerBuilder,\
io.undertow.server.handlers.encoding.EncodingHandler\\\$Builder,\
io.undertow.server.handlers.encoding.RequestEncodingHandler\\\$Builder,\
io.undertow.server.handlers.error.FileErrorPageHandler\\\$Builder,\
io.undertow.server.handlers.form.EagerFormParsingHandler\\\$Builder,\
io.undertow.server.handlers.proxy.ProxyHandlerBuilder,\
io.undertow.server.handlers.resource.ResourceHandler\\\$Builder,\
io.undertow.servlet.ServletExtension,\
io.undertow.servlet.attribute.ServletContextAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletNameAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRelativePathAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestCharacterEncodingAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestLineAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestLocaleAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestParameterAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestURLAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestedSessionIdAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestedSessionIdFromCookieAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletRequestedSessionIdValidAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletSessionAttribute\\\$Builder,\
io.undertow.servlet.attribute.ServletSessionIdAttribute\\\$Builder,\
io.undertow.servlet.handlers.MarkSecureHandler\\\$Builder,\
io.undertow.servlet.predicate.DirectoryPredicate\\\$Builder,\
io.undertow.servlet.predicate.DispatcherTypePredicate\\\$Builder,\
io.undertow.servlet.predicate.FilePredicate\\\$Builder,\
io.undertow.servlet.sse.ServerSentEventSCI,\
io.undertow.websockets.jsr.Bootstrap,\
io.undertow.websockets.jsr.DefaultContainerConfigurator,\
io.undertow.websockets.jsr.DefaultWebSocketClientSslProvider,\
io.undertow.websockets.jsr.UndertowContainerProvider,\
io.undertow.websockets.jsr.WebsocketClientSslProvider,\
jakarta.enterprise.inject.spi.Extension,\
jakarta.json.bind.spi.JsonbProvider,\
jakarta.json.spi.JsonProvider,\
jakarta.servlet.ServletContainerInitializer,\
jakarta.websocket.ContainerProvider,\
jakarta.websocket.server.ServerEndpointConfig\\\$Configurator,\
java.io.Closeable,\
java.io.Serializable,\
java.lang.AutoCloseable,\
java.lang.Cloneable,\
java.lang.Object,\
java.net.URLStreamHandlerFactory,\
java.net.spi.URLStreamHandlerProvider,\
java.nio.file.spi.FileSystemProvider,\
java.security.Provider,\
java.util.Dictionary,\
java.util.Hashtable,\
java.util.Map,\
java.util.Properties,\
java.util.logging.LogManager,\
javax.management.MBeanServerBuilder,\
javax.naming.spi.InitialContextFactory,\
javax.security.sasl.SaslClientFactory,\
javax.security.sasl.SaslServerFactory,\
javax.tools.JavaCompiler,\
javax.tools.OptionChecker,\
javax.tools.Tool,\
org.aesh.command.Command,\
org.apache.commons.logging.LogFactory,\
org.apache.commons.logging.impl.JBossLogFactory,\
org.apache.sshd.common.file.root.RootedFileSystemProvider,\
org.eclipse.jdt.internal.compiler.tool.EclipseCompiler,\
org.eclipse.jgit.lib.SignatureVerifierFactory,\
org.eclipse.jgit.lib.SignerFactory,\
org.eclipse.jgit.signing.ssh.SshSignatureVerifierFactory,\
org.eclipse.jgit.signing.ssh.SshSignerFactory,\
org.eclipse.jgit.transport.SshSessionFactory,\
org.eclipse.jgit.transport.sshd.SshdSessionFactory,\
org.eclipse.parsson.JsonProviderImpl,\
org.eclipse.yasson.JsonBindingProvider,\
org.glassfish.enterprise.concurrent.cdi.ConcurrentCDIExtension,\
org.infinispan.commons.api.query.geo.LatLng\\\$LatLngSchema,\
org.infinispan.commons.api.query.geo.LatLngSchemaImpl,\
org.infinispan.commons.jdkspecific.ClasspathURLStreamHandlerProvider,\
org.infinispan.protostream.GeneratedSchema,\
org.infinispan.protostream.SerializationContextInitializer,\
org.jboss.as.cli.impl.BootScriptInvoker,\
org.jboss.as.clustering.naming.NamespaceContextualizerFactory,\
org.jboss.as.controller.Extension,\
org.jboss.as.controller.Feature,\
org.jboss.as.controller.ModelControllerServiceInitialization,\
org.jboss.as.controller.client.impl.AdditionalBootCliScriptInvoker,\
org.jboss.as.controller.persistence.ConfigurationExtension,\
org.jboss.as.controller.persistence.yaml.YamlConfigurationExtension,\
org.jboss.as.controller.transform.ExtensionTransformerRegistration,\
org.jboss.as.controller.transform.SubsystemExtensionTransformerRegistration,\
org.jboss.as.ee.concurrent.AbstractConcurrencyImplementation,\
org.jboss.as.ee.concurrent.ConcurrencyImplementation,\
org.jboss.as.ee.concurrent.ConcurrencyImplementation30,\
org.jboss.as.ee.subsystem.EeExtension,\
org.jboss.as.host.controller.embedded.HostEmbeddedProcessBootstrap,\
org.jboss.as.jmx.JMXExtension,\
org.jboss.as.jmx.PluggableMBeanServerBuilder,\
org.jboss.as.jmx.model.ManagementModelIntegration,\
org.jboss.as.naming.subsystem.NamingExtension,\
org.jboss.as.quickstart.http_custom_mechanism.CustomMechanismFactory,\
org.jboss.as.remoting.RemotingExtension,\
org.jboss.as.remoting.RemotingTransformerRegistration,\
org.jboss.as.server.deployment.scanner.DeploymentScannerExtension,\
org.jboss.as.server.embedded.AbstractEmbeddedProcessBootstrap,\
org.jboss.as.server.embedded.StandaloneEmbeddedProcessBootstrap,\
org.jboss.common.beans.property.finder.DefaultPropertyEditorFinder,\
org.jboss.common.beans.property.finder.PropertyEditorFinder,\
org.jboss.common.beans.property.token.ArrayTokenizer,\
org.jboss.common.beans.property.token.GreedyTokenizer,\
org.jboss.ejb.client.EJBNamingContextFactory,\
org.jboss.ejb.client.EJBTransportProvider,\
org.jboss.ejb.client.legacy.DiscoveryLegacyConfiguration,\
org.jboss.ejb.client.legacy.ElytronLegacyConfiguration,\
org.jboss.ejb.client.legacy.RemotingLegacyConfiguration,\
org.jboss.ejb.protocol.remote.EJBMarshallingCompatibilityHelper,\
org.jboss.ejb.protocol.remote.EJBTransactionProvider,\
org.jboss.ejb.protocol.remote.RemoteEJBDiscoveryConfigurator,\
org.jboss.ejb.protocol.remote.RemoteTransportProvider,\
org.jboss.logmanager.LogManager,\
org.jboss.marshalling.ProviderDescriptor,\
org.jboss.marshalling.river.RiverProviderDescriptor,\
org.jboss.remoting3.spi.EndpointConfigurator,\
org.jboss.vfs.protocol.VfsUrlStreamHandlerFactory,\
org.jboss.vfs.protocol.VfsUrlStreamHandlerProvider,\
org.slf4j.impl.JBossSlf4jServiceProvider,\
org.slf4j.spi.SLF4JServiceProvider,\
org.wildfly.clustering.cache.batch.BatchContextualizerFactory,\
org.wildfly.clustering.cache.function.FunctionSerializationContextInitializer,\
org.wildfly.clustering.cache.infinispan.batch.TransactionalBatchContextualizerFactory,\
org.wildfly.clustering.context.ContextualizerFactory,\
org.wildfly.clustering.marshalling.protostream.AbstractSerializationContextInitializer,\
org.wildfly.clustering.marshalling.protostream.SerializationContextInitializer,\
org.wildfly.clustering.server.offset.OffsetSerializationContextInitializer,\
org.wildfly.clustering.server.util.UtilSerializationContextInitializer,\
org.wildfly.core.embedded.spi.EmbeddedProcessBootstrap,\
org.wildfly.core.instmgr.InstMgrInitialization,\
org.wildfly.core.instmgr.cli.InstMgrGroupCommand,\
org.wildfly.discovery.spi.ExternalDiscoveryConfigurator,\
org.wildfly.elytron.web.undertow.server.servlet.UndertowHttpServletRequestContext,\
org.wildfly.elytron.web.undertow.server.sni.SNIAlpnEngineManager,\
org.wildfly.extension.elytron.ElytronExtension,\
org.wildfly.extension.elytron.ElytronSubsystemTransformers,\
org.wildfly.extension.elytron._private.WildFlyAcmeClient,\
org.wildfly.extension.io.IOExtension,\
org.wildfly.extension.io.IOExtensionTransformerRegistration,\
org.wildfly.extension.requestcontroller.RequestControllerExtension,\
org.wildfly.extension.undertow.UndertowExtension,\
org.wildfly.extension.undertow.UndertowExtensionTransformerRegistration,\
org.wildfly.httpclient.naming.HttpNamingContextFactory,\
org.wildfly.httpclient.naming.HttpNamingProviderFactory,\
org.wildfly.naming.client.MarshallingCompatibilityHelper,\
org.wildfly.naming.client.NamingContextFactory,\
org.wildfly.naming.client.NamingProviderFactory,\
org.wildfly.naming.client.WildFlyInitialContextFactory,\
org.wildfly.naming.client.remote.RemoteNamingContextFactory,\
org.wildfly.naming.client.remote.RemoteNamingProviderFactory,\
org.wildfly.openssl.OpenSSLProvider,\
org.wildfly.security.VersionedProvider,\
org.wildfly.security.WildFlyElytronBaseProvider,\
org.wildfly.security.WildFlyElytronDigestProvider,\
org.wildfly.security.WildFlyElytronHttpBasicProvider,\
org.wildfly.security.WildFlyElytronHttpBearerProvider,\
org.wildfly.security.WildFlyElytronHttpClientCertProvider,\
org.wildfly.security.WildFlyElytronHttpDigestProvider,\
org.wildfly.security.WildFlyElytronHttpFormProvider,\
org.wildfly.security.WildFlyElytronHttpSpnegoProvider,\
org.wildfly.security.WildFlyElytronProvider,\
org.wildfly.security.auth.client.LegacyConfiguration,\
org.wildfly.security.auth.client.WildFlyElytronClientDefaultSSLContextProvider,\
org.wildfly.security.authz.jacc.HttpServletRequestContext,\
org.wildfly.security.credential.store.WildFlyElytronCredentialStoreProvider,\
org.wildfly.security.digest.WildFlyElytronDigestProvider,\
org.wildfly.security.dynamic.ssl.DynamicSSLContextImpl,\
org.wildfly.security.dynamic.ssl.DynamicSSLContextSPI,\
org.wildfly.security.http.HttpServerAuthenticationMechanismFactory,\
org.wildfly.security.http.basic.BasicMechanismFactory,\
org.wildfly.security.http.basic.WildFlyElytronHttpBasicProvider,\
org.wildfly.security.http.bearer.BearerMechanismFactory,\
org.wildfly.security.http.bearer.WildFlyElytronHttpBearerProvider,\
org.wildfly.security.http.cert.ClientCertMechanismFactory,\
org.wildfly.security.http.cert.WildFlyElytronHttpClientCertProvider,\
org.wildfly.security.http.digest.DigestMechanismFactory,\
org.wildfly.security.http.digest.WildFlyElytronHttpDigestProvider,\
org.wildfly.security.http.external.ExternalMechanismFactory,\
org.wildfly.security.http.external.WildFlyElytronHttpExternalProvider,\
org.wildfly.security.http.form.FormMechanismFactory,\
org.wildfly.security.http.form.WildFlyElytronHttpFormProvider,\
org.wildfly.security.http.spnego.SpnegoMechanismFactory,\
org.wildfly.security.http.spnego.WildFlyElytronHttpSpnegoProvider,\
org.wildfly.security.key.WildFlyElytronKeyProvider,\
org.wildfly.security.keystore.WildFlyElytronKeyStoreProvider,\
org.wildfly.security.password.WildFlyElytronPasswordProvider,\
org.wildfly.security.sasl.anonymous.AbstractAnonymousFactory,\
org.wildfly.security.sasl.anonymous.AnonymousClientFactory,\
org.wildfly.security.sasl.anonymous.AnonymousServerFactory,\
org.wildfly.security.sasl.anonymous.WildFlyElytronSaslAnonymousProvider,\
org.wildfly.security.sasl.digest.AbstractDigestFactory,\
org.wildfly.security.sasl.digest.DigestClientFactory,\
org.wildfly.security.sasl.digest.DigestServerFactory,\
org.wildfly.security.sasl.digest.WildFlyElytronSaslDigestProvider,\
org.wildfly.security.sasl.entity.EntitySaslClientFactory,\
org.wildfly.security.sasl.entity.EntitySaslServerFactory,\
org.wildfly.security.sasl.entity.WildFlyElytronSaslEntityProvider,\
org.wildfly.security.sasl.external.ExternalSaslClientFactory,\
org.wildfly.security.sasl.external.ExternalSaslServerFactory,\
org.wildfly.security.sasl.external.WildFlyElytronSaslExternalProvider,\
org.wildfly.security.sasl.gs2.Gs2SaslClientFactory,\
org.wildfly.security.sasl.gs2.Gs2SaslServerFactory,\
org.wildfly.security.sasl.gs2.WildFlyElytronSaslGs2Provider,\
org.wildfly.security.sasl.gssapi.AbstractGssapiFactory,\
org.wildfly.security.sasl.gssapi.GssapiClientFactory,\
org.wildfly.security.sasl.gssapi.GssapiServerFactory,\
org.wildfly.security.sasl.gssapi.WildFlyElytronSaslGssapiProvider,\
org.wildfly.security.sasl.localuser.LocalUserClientFactory,\
org.wildfly.security.sasl.localuser.LocalUserSaslFactory,\
org.wildfly.security.sasl.localuser.LocalUserServerFactory,\
org.wildfly.security.sasl.localuser.WildFlyElytronSaslLocalUserProvider,\
org.wildfly.security.sasl.oauth2.OAuth2SaslClientFactory,\
org.wildfly.security.sasl.oauth2.OAuth2SaslServerFactory,\
org.wildfly.security.sasl.oauth2.WildFlyElytronSaslOAuth2Provider,\
org.wildfly.security.sasl.otp.OTPSaslClientFactory,\
org.wildfly.security.sasl.otp.OTPSaslServerFactory,\
org.wildfly.security.sasl.otp.WildFlyElytronSaslOTPProvider,\
org.wildfly.security.sasl.plain.PlainSaslClientFactory,\
org.wildfly.security.sasl.plain.PlainSaslServerFactory,\
org.wildfly.security.sasl.plain.WildFlyElytronSaslPlainProvider,\
org.wildfly.security.sasl.scram.ScramSaslClientFactory,\
org.wildfly.security.sasl.scram.ScramSaslServerFactory,\
org.wildfly.security.sasl.scram.WildFlyElytronSaslScramProvider,\
org.wildfly.security.sasl.util.AbstractSaslFactory,\
org.wildfly.security.x500.cert.acme.AcmeClientSpi,\
org.wildfly.subsystem.SubsystemExtension,\
org.wildfly.transaction.client.naming.txn.TxnNamingContextFactory,\
org.wildfly.transaction.client.provider.remoting.RemotingFallbackPeerProvider,\
org.xnio.XnioProvider,\
org.xnio.nio.NioXnioProvider,\
ORG.FOO.CLASSES.MANUALLY.ADDED,\
com.sun.el.ExpressionFactoryImpl,\
io.smallrye.common.expression,\
io.smallrye.common.expression.Expression\\\$Flag,\
io.undertow.UndertowLogger,\
io.undertow.UndertowLogger_\\\$logger,\
io.undertow.UndertowMessages,\
io.undertow.UndertowMessages_\\\$bundle,\
io.undertow.Version,\
io.undertow.attribute,\
io.undertow.server.DirectByteBufferDeallocator,\
io.undertow.server.protocol.http.ServiceLoaderInitializer,\
io.undertow.servlet.UndertowServletLogger,\
io.undertow.servlet.UndertowServletLogger_\\\$logger,\
io.undertow.servlet.UndertowServletMessages,\
io.undertow.servlet.UndertowServletMessages_\\\$bundle,\
io.undertow.servlet.api.ServletStackTraces,\
io.undertow.servlet.sse.ServerSentEventSCI,\
io.undertow.servlet.util.ConstructorInstanceFactory,\
io.undertow.util.AttachmentKey,\
io.undertow.util.ConcurrentDirectDeque,\
io.undertow.util.FastConcurrentDirectDeque,\
io.undertow.util,\
io.undertow.util.SimpleAttachmentKey,\
io.undertow.websockets.core.WebSocketMessages,\
io.undertow.websockets.core.WebSocketMessages_\\\$logger,\
io.undertow.websockets.core.WebSocketMessages_\\\$bundle,\
io.undertow.websockets.core.WebSocketLogger,\
io.undertow.websockets.core.WebSocketLogger_\\\$logger,\
io.undertow.websockets.jsr.Bootstrap,\
io.undertow.websockets.jsr.Bootstrap\\\$1,\
io.undertow.websockets.jsr.Bootstrap\\\$WebSocketListener,\
io.undertow.websockets.jsr.DefaultWebSocketClientSslProvider,\
io.undertow.websockets.jsr.JsrWebSocketFilter\\\$LogoutListener,\
io.undertow.websockets.jsr.WebSocketDeploymentInfo,\
io.undertow.websockets.jsr.WebSocketDeploymentInfo\\\$2,\
io.undertow.websockets.jsr.JsrWebSocketLogger,\
io.undertow.websockets.jsr.JsrWebSocketLogger_\\\$logger,\
io.undertow.websockets.jsr.JsrWebSocketMessages,\
io.undertow.websockets.jsr.JsrWebSocketMessages_\\\$bundle,\
jakarta.annotation.PostConstruct,\
jakarta.el,\
jakarta.json,\
jakarta.servlet.annotation,\
jakarta.servlet.http.HttpSessionListener,\
jakarta.servlet.ServletContextListener,\
jakarta.servlet.jsp.JspApplicationContext,\
jakarta.servlet.jsp.JspFactory,\
jakarta.servlet.jsp.jstl.tlv.PermittedTaglibsTLV,\
jakarta.websocket.server.ServerEndpoint,\
jakarta.websocket.OnMessage,\
jakarta.websocket.OnOpen,\
jakarta.websocket.OnClose,\
jakarta.websocket.OnError,\
java.lang.annotation.Annotation,\
java.util.EventListener,\
launcher.Launcher,\
launcher.Cache,\
org.apache.jasper.compiler.JspRuntimeContext,\
org.apache.jasper.runtime.JspApplicationContextImpl,\
org.apache.jasper.runtime.JspFactoryImpl,\
org.apache.jasper.servlet.JspServlet,\
org.apache.sshd.common.file.root.RootedFileSystemProvider,\
org.eclipse.parsson,\
org.glassfish.expressly,\
org.jboss.as.controller,\
org.jboss.as.controller.PersistentResourceDefinition,\
org.jboss.as.controller.SimpleResourceDefinition,\
org.jboss.as.controller.ResourceDefinition\\\$MinimalResourceDefinition,\
org.jboss.as.controller.xml,\
org.jboss.as.controller.persistence,\
org.jboss.as.controller.persistence.xml,\
org.jboss.as.domain.http.server.logging.HttpServerLogger,\
org.jboss.as.domain.http.server.logging.HttpServerLogger_\\\$logger,\
org.jboss.as.ee.component.ComponentRegistry,\
org.jboss.as.ee.logging,\
org.jboss.as.ee.concurrent.AbstractConcurrencyImplementation,\
org.jboss.as.ee.concurrent.ConcurrencyImplementation,\
org.jboss.as.ee.concurrent.ConcurrencyImplementation30,\
org.jboss.as.ee.subsystem.EeExtension,\
org.jboss.as.jmx.model.ManagementModelIntegration,\
org.jboss.as.naming,\
org.jboss.as.naming.context.ObjectFactoryBuilder,\
org.jboss.as.naming.deployment.JdkDependenciesProcessor,\
org.jboss.as.naming.logging,\
org.jboss.as.naming.subsystem.NamingExtension,\
org.jboss.as.process.logging.ProcessLogger_\\\$logger,\
org.jboss.as.protocol.logging.ProtocolLogger,\
org.jboss.as.protocol.logging.ProtocolLogger_\\\$logger,\
org.jboss.as.remoting.RemotingServices,\
org.jboss.as.repository.logging,\
org.jboss.as.server,\
org.jboss.as.version,\
org.jboss.as.web.common,\
org.jboss.dmr,\
org.jboss.jandex.DotName,\
org.jboss.jandex.DotName\\\$1,\
org.jboss.logging,\
org.jboss.logmanager,\
org.jboss.metadata.parser.servlet.Version,\
org.jboss.metadata.parser.util.Version,\
org.jboss.modules,\
org.jboss.msc.service.IdentityHashSet,\
org.jboss.msc.service.WritableValueImpl,\
org.jboss.msc.service.ServiceLogger,\
org.jboss.msc.service.ServiceLogger_\\\$logger,\
org.jboss.msc.service.ServiceName,\
org.jboss.msc.service.ServiceRegistrationImpl,\
org.jboss.msc.service.Lockable,\
org.jboss.msc.service.Dependency,\
org.jboss.msc.value.Value,\
org.jboss.msc.service.ReadableValueImpl,\
org.jboss.msc.value,\
org.jboss.as.remoting.logging.RemotingLogger,\
org.jboss.as.remoting.logging.RemotingLogger_\\\$logger,\
org.jboss.remoting3.Version,\
org.jboss.remoting3._private.Messages,\
org.jboss.remoting3._private.Messages_\\\$logger,\
org.jboss.staxmapper,\
org.jboss.threads.Messages,\
org.jboss.threads.Messages_\\\$logger,\
org.jboss.vfs,\
org.slf4j.impl.Slf4jLogger,\
org.wildfly.common,\
org.wildfly.controller,\
org.wildfly.core.embedded.spi,\
org.wildfly.core.instmgr.InstMgrInitialization,\
org.wildfly.extension.elytron.ElytronExtension,\
org.wildfly.extension.elytron.PermissionsPreLoader,\
org.wildfly.extension.elytron._private.WildFlyAcmeClient,\
org.wildfly.extension.elytron._private.ElytronSubsystemMessages,\
org.wildfly.extension.elytron._private.ElytronSubsystemMessages_\\\$logger,\
org.wildfly.extension.io,\
org.wildfly.extension.undertow,\
org.wildfly.extension.undertow.graal.DeploymentInitializer,\
org.wildfly.extension.undertow.AbstractHttpListenerResourceDefinition,\
org.wildfly.extension.undertow.AjpListenerResourceDefinition,\
org.wildfly.extension.undertow.HttpsListenerResourceDefinition,\
org.wildfly.extension.undertow.ListenerResourceDefinition,\
org.wildfly.extension.undertow.ServletContainerAdd,\
org.wildfly.extension.undertow.UndertowExtension,\
org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService,\
org.wildfly.extension.undertow.deployment.JspInitializationListener,\
org.wildfly.extension.undertow.filters,\
org.wildfly.extension.undertow.filters.AbstractFilterDefinition,\
org.wildfly.extension.undertow.filters.ModClusterDefinition,\
org.wildfly.io.OptionAttributeDefinition,\
org.wildfly.naming.java.permission,\
org.wildfly.openssl.OpenSSLProvider,\
org.wildfly.security,\
org.wildfly.service.descriptor,\
org.wildfly.subsystem,\
org.xnio.FileAccess,\
org.xnio.LocalSocketAddress,\
org.xnio.Option,\
org.xnio.Option\\\$1,\
org.xnio.Option\\\$2,\
org.xnio.Option\\\$3,\
org.xnio.Option\\\$4,\
org.xnio.Option\\\$5,\
org.xnio.Option\\\$6,\
org.xnio.Option\\\$7,\
org.xnio.Option\\\$8,\
org.xnio.Option\\\$9,\
org.xnio.Option\\\$10,\
org.xnio.OptionMap,\
org.xnio.SequenceOption,\
org.xnio.SingleOption,\
org.xnio.SslClientAuthMode,\
org.xnio.Version,\
org.xnio._private.Messages,\
org.xnio._private.Messages_\\\$logger,\
org.xnio.Xnio,\
org.xnio.Xnio\\\$1,\
org.xnio.nio.Log,\
org.xnio.nio.Log_\\\$logger,\
org.xnio.nio.NioXnio\\\$DefaultSelectorCreator,\
org.xnio.nio.NioXnio\\\$4,\
org.xnio.nio.NioXnio,\
org.xnio.nio.NioXnioProvider \
--initialize-at-run-time=org.jboss.as.server.services.net,\
org.jboss.as.server.deployment.module.TempFileProviderService,\
org.jboss.as.server.DomainServerCommunicationServices,\
org.jboss.as.server.operations.NativeManagementServices \
--enable-url-protocols=jar,data \
--enable-sbom=false \
--trace-object-instantiation=java.lang.ref.Cleaner \
-cp ${current_dir}/min-core-server/jboss-modules.jar:wildfly-substitutions/target/wildfly-substitutions.jar "

echo "$cmd" > "./build-image.sh"
chmod +x ./build-image.sh
./build-image.sh