current_dir=$(pwd)

IFS=$'\n'
array=($(find ./min-core-server/modules/system/layers/base/ -name \*.jar))
unset IFS

arraylength=${#array[@]}

cmd="
native-image -jar module-launcher/target/ModuleLauncher-1.0-SNAPSHOT.jar \
wildfly-launcher \
-Dorg.wildfly.graal.deployment.module=deployment.helloworld.war \
-Dorg.jboss.modules.record.classes=pre.compiled.jsps,org.jboss.as.quickstarts.helloworld,org.jboss.quickstarts.websocket,org.jboss.as.quickstarts.websocket_hello,org.jboss.as.quickstart.http_custom_mechanism \
-Djboss.home.dir=${current_dir}/min-core-server \
-Djava.util.logging.manager=org.jboss.logmanager.LogManager \
-Djboss.modules.system.pkgs=org.jboss.modules,launcher,org.jboss.logmanager,org.jboss.logging \
-Dlogging.configuration=file:${current_dir}/min-core-server/standalone/configuration/logging.properties \
-Dorg.jboss.boot.log.file=${current_dir}/min-core-server/standalone/log/server.log \
-Duser.home==/Users/foo \
-Djboss.server.base.dir=${current_dir}/min-core-server/standalone \
-H:+PrintClassInitialization \
--initialize-at-build-time=\
launcher,\
java.beans,\
sun.security.jgss.GSSManagerImpl,\
com.github,\
com.github.benmanes,\
com.github.benmanes.caffeine,\
com.github.benmanes.caffeine.cache,\
com.github.benmanes.caffeine.cache.stats,\
com.googlecode,\
com.googlecode.javaewah,\
com.googlecode.javaewah.datastructure,\
com.googlecode.javaewah.symmetric,\
com.googlecode.javaewah32,\
com.googlecode.javaewah32.symmetric,\
com.squareup,\
com.squareup.protoparser,\
com.sun,\
com.sun.el,\
io.reactivex,\
io.reactivex.rxjava3,\
io.reactivex.rxjava3.annotations,\
io.reactivex.rxjava3.core,\
io.reactivex.rxjava3.disposables,\
io.reactivex.rxjava3.exceptions,\
io.reactivex.rxjava3.flowables,\
io.reactivex.rxjava3.functions,\
io.reactivex.rxjava3.internal,\
io.reactivex.rxjava3.internal.disposables,\
io.reactivex.rxjava3.internal.functions,\
io.reactivex.rxjava3.internal.fuseable,\
io.reactivex.rxjava3.internal.jdk8,\
io.reactivex.rxjava3.internal.observers,\
io.reactivex.rxjava3.internal.operators,\
io.reactivex.rxjava3.internal.operators.completable,\
io.reactivex.rxjava3.internal.operators.flowable,\
io.reactivex.rxjava3.internal.operators.maybe,\
io.reactivex.rxjava3.internal.operators.mixed,\
io.reactivex.rxjava3.internal.operators.observable,\
io.reactivex.rxjava3.internal.operators.parallel,\
io.reactivex.rxjava3.internal.operators.single,\
io.reactivex.rxjava3.internal.queue,\
io.reactivex.rxjava3.internal.schedulers,\
io.reactivex.rxjava3.internal.subscribers,\
io.reactivex.rxjava3.internal.subscriptions,\
io.reactivex.rxjava3.internal.util,\
io.reactivex.rxjava3.observables,\
io.reactivex.rxjava3.observers,\
io.reactivex.rxjava3.operators,\
io.reactivex.rxjava3.parallel,\
io.reactivex.rxjava3.plugins,\
io.reactivex.rxjava3.processors,\
io.reactivex.rxjava3.schedulers,\
io.reactivex.rxjava3.subjects,\
io.reactivex.rxjava3.subscribers,\
io.smallrye,\
io.smallrye.common,\
io.smallrye.common.constraint,\
io.smallrye.common.cpu,\
io.smallrye.common.expression,\
io.smallrye.common.function,\
io.smallrye.common.net,\
io.smallrye.common.os,\
io.undertow,\
io.undertow.attribute,\
io.undertow.channels,\
io.undertow.client,\
io.undertow.client.ajp,\
io.undertow.client.http,\
io.undertow.client.http2,\
io.undertow.conduits,\
io.undertow.connector,\
io.undertow.io,\
io.undertow.jsp,\
io.undertow.predicate,\
io.undertow.protocols,\
io.undertow.protocols.ajp,\
io.undertow.protocols.alpn,\
io.undertow.protocols.http2,\
io.undertow.protocols.ssl,\
io.undertow.security,\
io.undertow.security.api,\
io.undertow.security.handlers,\
io.undertow.security.idm,\
io.undertow.security.impl,\
io.undertow.server,\
io.undertow.server.handlers,\
io.undertow.server.handlers.accesslog,\
io.undertow.server.handlers.builder,\
io.undertow.server.handlers.cache,\
io.undertow.server.handlers.encoding,\
io.undertow.server.handlers.error,\
io.undertow.server.handlers.form,\
io.undertow.server.handlers.proxy,\
io.undertow.server.handlers.proxy.mod_cluster,\
io.undertow.server.handlers.resource,\
io.undertow.server.handlers.sse,\
io.undertow.server.protocol,\
io.undertow.server.protocol.ajp,\
io.undertow.server.protocol.framed,\
io.undertow.server.protocol.http,\
io.undertow.server.protocol.http2,\
io.undertow.server.protocol.proxy,\
io.undertow.server.session,\
io.undertow.servlet,\
io.undertow.servlet.api,\
io.undertow.servlet.attribute,\
io.undertow.servlet.compat,\
io.undertow.servlet.compat.rewrite,\
io.undertow.servlet.core,\
io.undertow.servlet.handlers,\
io.undertow.servlet.handlers.security,\
io.undertow.servlet.predicate,\
io.undertow.servlet.spec,\
io.undertow.servlet.sse,\
io.undertow.servlet.util,\
io.undertow.servlet.websockets,\
io.undertow.util,\
io.undertow.websockets,\
io.undertow.websockets.client,\
io.undertow.websockets.core,\
io.undertow.websockets.core.function,\
io.undertow.websockets.core.protocol,\
io.undertow.websockets.core.protocol.version07,\
io.undertow.websockets.core.protocol.version08,\
io.undertow.websockets.core.protocol.version13,\
io.undertow.websockets.extensions,\
io.undertow.websockets.jsr,\
io.undertow.websockets.jsr.annotated,\
io.undertow.websockets.jsr.handshake,\
io.undertow.websockets.jsr.util,\
io.undertow.websockets.spi,\
jakarta.annotation,\
jakarta.annotation.security,\
jakarta.annotation.sql,\
jakarta.decorator,\
jakarta.ejb,\
jakarta.ejb.embeddable,\
jakarta.ejb.spi,\
jakarta.el,\
jakarta.enterprise,\
jakarta.enterprise.concurrent,\
jakarta.enterprise.concurrent.spi,\
jakarta.enterprise.context,\
jakarta.enterprise.context.control,\
jakarta.enterprise.context.spi,\
jakarta.enterprise.event,\
jakarta.enterprise.inject,\
jakarta.enterprise.inject.build,\
jakarta.enterprise.inject.build.compatible,\
jakarta.enterprise.inject.build.compatible.spi,\
jakarta.enterprise.inject.literal,\
jakarta.enterprise.inject.se,\
jakarta.enterprise.inject.spi,\
jakarta.enterprise.inject.spi.configurator,\
jakarta.enterprise.lang,\
jakarta.enterprise.lang.model,\
jakarta.enterprise.lang.model.declarations,\
jakarta.enterprise.lang.model.types,\
jakarta.enterprise.util,\
jakarta.inject,\
jakarta.interceptor,\
jakarta.json,\
jakarta.json.bind,\
jakarta.json.bind.adapter,\
jakarta.json.bind.annotation,\
jakarta.json.bind.config,\
jakarta.json.bind.serializer,\
jakarta.json.bind.spi,\
jakarta.json.spi,\
jakarta.json.stream,\
jakarta.resource,\
jakarta.resource.cci,\
jakarta.resource.spi,\
jakarta.resource.spi.endpoint,\
jakarta.resource.spi.security,\
jakarta.resource.spi.work,\
jakarta.security,\
jakarta.security.auth,\
jakarta.security.auth.message,\
jakarta.security.auth.message.callback,\
jakarta.security.auth.message.config,\
jakarta.security.auth.message.module,\
jakarta.security.jacc,\
jakarta.servlet,\
jakarta.servlet.annotation,\
jakarta.servlet.descriptor,\
jakarta.servlet.http,\
jakarta.servlet.jsp,\
jakarta.servlet.jsp.el,\
jakarta.servlet.jsp.jstl,\
jakarta.servlet.jsp.jstl.core,\
jakarta.servlet.jsp.jstl.fmt,\
jakarta.servlet.jsp.jstl.sql,\
jakarta.servlet.jsp.jstl.tlv,\
jakarta.servlet.jsp.tagext,\
jakarta.servlet.resources,\
jakarta.transaction,\
jakarta.websocket,\
jakarta.websocket.server,\
javax.json,\
javax.json.spi,\
javax.json.stream,\
net.jcip,\
net.jcip.annotations,\
org.aesh,\
org.aesh.command,\
org.aesh.command.activator,\
org.aesh.command.alias,\
org.aesh.command.builder,\
org.aesh.command.completer,\
org.aesh.command.container,\
org.aesh.command.converter,\
org.aesh.command.export,\
org.aesh.command.impl,\
org.aesh.command.impl.activator,\
org.aesh.command.impl.completer,\
org.aesh.command.impl.container,\
org.aesh.command.impl.converter,\
org.aesh.command.impl.internal,\
org.aesh.command.impl.invocation,\
org.aesh.command.impl.operator,\
org.aesh.command.impl.parser,\
org.aesh.command.impl.populator,\
org.aesh.command.impl.registry,\
org.aesh.command.impl.renderer,\
org.aesh.command.impl.result,\
org.aesh.command.impl.shell,\
org.aesh.command.impl.validator,\
org.aesh.command.invocation,\
org.aesh.command.man,\
org.aesh.command.man.parser,\
org.aesh.command.map,\
org.aesh.command.operator,\
org.aesh.command.option,\
org.aesh.command.parser,\
org.aesh.command.populator,\
org.aesh.command.registry,\
org.aesh.command.renderer,\
org.aesh.command.result,\
org.aesh.command.settings,\
org.aesh.command.shell,\
org.aesh.command.validator,\
org.aesh.comparators,\
org.aesh.complete,\
org.aesh.constants,\
org.aesh.converter,\
org.aesh.extensions,\
org.aesh.extensions.cat,\
org.aesh.extensions.cd,\
org.aesh.extensions.choice,\
org.aesh.extensions.clear,\
org.aesh.extensions.echo,\
org.aesh.extensions.example,\
org.aesh.extensions.exit,\
org.aesh.extensions.grep,\
org.aesh.extensions.groovy,\
org.aesh.extensions.harlem,\
org.aesh.extensions.highlight,\
org.aesh.extensions.highlight.encoder,\
org.aesh.extensions.highlight.scanner,\
org.aesh.extensions.highlight.scanner.java,\
org.aesh.extensions.less,\
org.aesh.extensions.ls,\
org.aesh.extensions.matrix,\
org.aesh.extensions.mkdir,\
org.aesh.extensions.more,\
org.aesh.extensions.mv,\
org.aesh.extensions.pushdpopd,\
org.aesh.extensions.pwd,\
org.aesh.extensions.rm,\
org.aesh.extensions.touch,\
org.aesh.extensions.tty,\
org.aesh.graphics,\
org.aesh.impl,\
org.aesh.impl.util,\
org.aesh.io,\
org.aesh.io.filter,\
org.aesh.io.scanner,\
org.aesh.parser,\
org.aesh.readline,\
org.aesh.readline.action,\
org.aesh.readline.action.mappings,\
org.aesh.readline.alias,\
org.aesh.readline.completion,\
org.aesh.readline.cursor,\
org.aesh.readline.editing,\
org.aesh.readline.history,\
org.aesh.readline.paste,\
org.aesh.readline.terminal,\
org.aesh.readline.terminal.formatting,\
org.aesh.readline.terminal.impl,\
org.aesh.readline.terminal.utils,\
org.aesh.readline.tty,\
org.aesh.readline.tty.terminal,\
org.aesh.readline.undo,\
org.aesh.readline.util,\
org.aesh.selector,\
org.aesh.terminal,\
org.aesh.terminal.io,\
org.aesh.terminal.tty,\
org.aesh.terminal.utils,\
org.aesh.util,\
org.aesh.util.completer,\
org.aesh.util.graal,\
org.apache,\
org.apache.commons,\
org.apache.commons.cli,\
org.apache.commons.cli.help,\
org.apache.commons.lang3,\
org.apache.commons.lang3.arch,\
org.apache.commons.lang3.builder,\
org.apache.commons.lang3.compare,\
org.apache.commons.lang3.concurrent,\
org.apache.commons.lang3.concurrent.locks,\
org.apache.commons.lang3.event,\
org.apache.commons.lang3.exception,\
org.apache.commons.lang3.function,\
org.apache.commons.lang3.math,\
org.apache.commons.lang3.mutable,\
org.apache.commons.lang3.reflect,\
org.apache.commons.lang3.stream,\
org.apache.commons.lang3.text,\
org.apache.commons.lang3.text.translate,\
org.apache.commons.lang3.time,\
org.apache.commons.lang3.tuple,\
org.apache.commons.lang3.util,\
org.apache.commons.logging,\
org.apache.commons.logging.impl,\
org.apache.http,\
org.apache.http.annotation,\
org.apache.http.auth,\
org.apache.http.auth.params,\
org.apache.http.client,\
org.apache.http.client.config,\
org.apache.http.client.entity,\
org.apache.http.client.methods,\
org.apache.http.client.params,\
org.apache.http.client.protocol,\
org.apache.http.client.utils,\
org.apache.http.concurrent,\
org.apache.http.config,\
org.apache.http.conn,\
org.apache.http.conn.params,\
org.apache.http.conn.routing,\
org.apache.http.conn.scheme,\
org.apache.http.conn.socket,\
org.apache.http.conn.ssl,\
org.apache.http.conn.util,\
org.apache.http.cookie,\
org.apache.http.cookie.params,\
org.apache.http.entity,\
org.apache.http.impl,\
org.apache.http.impl.auth,\
org.apache.http.impl.bootstrap,\
org.apache.http.impl.client,\
org.apache.http.impl.conn,\
org.apache.http.impl.conn.tsccm,\
org.apache.http.impl.cookie,\
org.apache.http.impl.entity,\
org.apache.http.impl.execchain,\
org.apache.http.impl.io,\
org.apache.http.impl.pool,\
org.apache.http.io,\
org.apache.http.message,\
org.apache.http.params,\
org.apache.http.pool,\
org.apache.http.protocol,\
org.apache.http.ssl,\
org.apache.http.util,\
org.apache.jasper,\
org.apache.jasper.compiler,\
org.apache.jasper.compiler.tagplugin,\
org.apache.jasper.deploy,\
org.apache.jasper.el,\
org.apache.jasper.runtime,\
org.apache.jasper.security,\
org.apache.jasper.servlet,\
org.apache.jasper.tagplugins,\
org.apache.jasper.tagplugins.jstl,\
org.apache.jasper.tagplugins.jstl.core,\
org.apache.jasper.util,\
org.apache.jasper.xmlparser,\
org.apache.logging,\
org.apache.logging.log4j,\
org.apache.logging.log4j.internal,\
org.apache.logging.log4j.message,\
org.apache.logging.log4j.simple,\
org.apache.logging.log4j.spi,\
org.apache.logging.log4j.status,\
org.apache.logging.log4j.util,\
org.apache.logging.log4j.util.internal,\
org.apache.sshd,\
org.apache.sshd.agent,\
org.apache.sshd.agent.common,\
org.apache.sshd.agent.local,\
org.apache.sshd.agent.unix,\
org.apache.sshd.certificate,\
org.apache.sshd.client,\
org.apache.sshd.client.auth,\
org.apache.sshd.client.auth.hostbased,\
org.apache.sshd.client.auth.keyboard,\
org.apache.sshd.client.auth.password,\
org.apache.sshd.client.auth.pubkey,\
org.apache.sshd.client.channel,\
org.apache.sshd.client.channel.exit,\
org.apache.sshd.client.config,\
org.apache.sshd.client.config.hosts,\
org.apache.sshd.client.config.keys,\
org.apache.sshd.client.future,\
org.apache.sshd.client.global,\
org.apache.sshd.client.kex,\
org.apache.sshd.client.keyverifier,\
org.apache.sshd.client.session,\
org.apache.sshd.client.session.forward,\
org.apache.sshd.client.simple,\
org.apache.sshd.client.subsystem,\
org.apache.sshd.common,\
org.apache.sshd.common.auth,\
org.apache.sshd.common.channel,\
org.apache.sshd.common.channel.exception,\
org.apache.sshd.common.channel.throttle,\
org.apache.sshd.common.cipher,\
org.apache.sshd.common.compression,\
org.apache.sshd.common.config,\
org.apache.sshd.common.config.keys,\
org.apache.sshd.common.config.keys.impl,\
org.apache.sshd.common.config.keys.loader,\
org.apache.sshd.common.config.keys.loader.openssh,\
org.apache.sshd.common.config.keys.loader.openssh.kdf,\
org.apache.sshd.common.config.keys.loader.pem,\
org.apache.sshd.common.config.keys.loader.ssh2,\
org.apache.sshd.common.config.keys.u2f,\
org.apache.sshd.common.config.keys.writer,\
org.apache.sshd.common.config.keys.writer.openssh,\
org.apache.sshd.common.digest,\
org.apache.sshd.common.file,\
org.apache.sshd.common.file.nativefs,\
org.apache.sshd.common.file.nonefs,\
org.apache.sshd.common.file.root,\
org.apache.sshd.common.file.util,\
org.apache.sshd.common.file.virtualfs,\
org.apache.sshd.common.forward,\
org.apache.sshd.common.future,\
org.apache.sshd.common.global,\
org.apache.sshd.common.helpers,\
org.apache.sshd.common.io,\
org.apache.sshd.common.io.nio2,\
org.apache.sshd.common.kex,\
org.apache.sshd.common.kex.dh,\
org.apache.sshd.common.kex.extension,\
org.apache.sshd.common.kex.extension.parser,\
org.apache.sshd.common.keyprovider,\
org.apache.sshd.common.mac,\
org.apache.sshd.common.net,\
org.apache.sshd.common.random,\
org.apache.sshd.common.session,\
org.apache.sshd.common.session.helpers,\
org.apache.sshd.common.signature,\
org.apache.sshd.common.util,\
org.apache.sshd.common.util.buffer,\
org.apache.sshd.common.util.buffer.keys,\
org.apache.sshd.common.util.closeable,\
org.apache.sshd.common.util.functors,\
org.apache.sshd.common.util.helper,\
org.apache.sshd.common.util.io,\
org.apache.sshd.common.util.io.der,\
org.apache.sshd.common.util.io.functors,\
org.apache.sshd.common.util.io.input,\
org.apache.sshd.common.util.io.output,\
org.apache.sshd.common.util.io.resource,\
org.apache.sshd.common.util.logging,\
org.apache.sshd.common.util.net,\
org.apache.sshd.common.util.security,\
org.apache.sshd.common.util.security.bouncycastle,\
org.apache.sshd.common.util.security.eddsa,\
org.apache.sshd.common.util.security.eddsa.bouncycastle,\
org.apache.sshd.common.util.security.eddsa.generic,\
org.apache.sshd.common.util.threads,\
org.apache.sshd.core,\
org.apache.sshd.server,\
org.apache.sshd.server.auth,\
org.apache.sshd.server.auth.gss,\
org.apache.sshd.server.auth.hostbased,\
org.apache.sshd.server.auth.keyboard,\
org.apache.sshd.server.auth.password,\
org.apache.sshd.server.auth.pubkey,\
org.apache.sshd.server.channel,\
org.apache.sshd.server.command,\
org.apache.sshd.server.config,\
org.apache.sshd.server.config.keys,\
org.apache.sshd.server.forward,\
org.apache.sshd.server.global,\
org.apache.sshd.server.jaas,\
org.apache.sshd.server.kex,\
org.apache.sshd.server.keyprovider,\
org.apache.sshd.server.session,\
org.apache.sshd.server.shell,\
org.apache.sshd.server.subsystem,\
org.apache.sshd.server.x11,\
org.apache.taglibs,\
org.apache.taglibs.standard,\
org.apache.taglibs.standard.extra,\
org.apache.taglibs.standard.extra.spath,\
org.apache.taglibs.standard.functions,\
org.apache.taglibs.standard.lang,\
org.apache.taglibs.standard.lang.jstl,\
org.apache.taglibs.standard.lang.jstl.parser,\
org.apache.taglibs.standard.lang.support,\
org.apache.taglibs.standard.resources,\
org.apache.taglibs.standard.tag,\
org.apache.taglibs.standard.tag.common,\
org.apache.taglibs.standard.tag.common.core,\
org.apache.taglibs.standard.tag.common.fmt,\
org.apache.taglibs.standard.tag.common.sql,\
org.apache.taglibs.standard.tag.common.xml,\
org.apache.taglibs.standard.tag.el,\
org.apache.taglibs.standard.tag.el.core,\
org.apache.taglibs.standard.tag.el.fmt,\
org.apache.taglibs.standard.tag.el.sql,\
org.apache.taglibs.standard.tag.el.xml,\
org.apache.taglibs.standard.tag.rt,\
org.apache.taglibs.standard.tag.rt.core,\
org.apache.taglibs.standard.tag.rt.fmt,\
org.apache.taglibs.standard.tag.rt.sql,\
org.apache.taglibs.standard.tag.rt.xml,\
org.apache.taglibs.standard.tei,\
org.apache.taglibs.standard.tlv,\
org.apache.tomcat,\
org.apache.tomcat.util,\
org.apache.tomcat.util.descriptor,\
org.apache.tomcat.util.scan,\
org.apache.tomcat.util.security,\
org.bouncycastle,\
org.bouncycastle.apache,\
org.bouncycastle.apache.bzip2,\
org.bouncycastle.asn1,\
org.bouncycastle.asn1.anssi,\
org.bouncycastle.asn1.bc,\
org.bouncycastle.asn1.bsi,\
org.bouncycastle.asn1.cmc,\
org.bouncycastle.asn1.cmp,\
org.bouncycastle.asn1.cms,\
org.bouncycastle.asn1.cms.ecc,\
org.bouncycastle.asn1.crmf,\
org.bouncycastle.asn1.cryptlib,\
org.bouncycastle.asn1.cryptopro,\
org.bouncycastle.asn1.dvcs,\
org.bouncycastle.asn1.eac,\
org.bouncycastle.asn1.edec,\
org.bouncycastle.asn1.esf,\
org.bouncycastle.asn1.ess,\
org.bouncycastle.asn1.est,\
org.bouncycastle.asn1.gm,\
org.bouncycastle.asn1.gnu,\
org.bouncycastle.asn1.iana,\
org.bouncycastle.asn1.icao,\
org.bouncycastle.asn1.isara,\
org.bouncycastle.asn1.isismtt,\
org.bouncycastle.asn1.isismtt.ocsp,\
org.bouncycastle.asn1.isismtt.x509,\
org.bouncycastle.asn1.iso,\
org.bouncycastle.asn1.kisa,\
org.bouncycastle.asn1.microsoft,\
org.bouncycastle.asn1.misc,\
org.bouncycastle.asn1.mod,\
org.bouncycastle.asn1.mozilla,\
org.bouncycastle.asn1.nist,\
org.bouncycastle.asn1.nsri,\
org.bouncycastle.asn1.ntt,\
org.bouncycastle.asn1.ocsp,\
org.bouncycastle.asn1.oiw,\
org.bouncycastle.asn1.pkcs,\
org.bouncycastle.asn1.rosstandart,\
org.bouncycastle.asn1.sec,\
org.bouncycastle.asn1.smime,\
org.bouncycastle.asn1.teletrust,\
org.bouncycastle.asn1.tsp,\
org.bouncycastle.asn1.ua,\
org.bouncycastle.asn1.util,\
org.bouncycastle.asn1.x500,\
org.bouncycastle.asn1.x500.style,\
org.bouncycastle.asn1.x509,\
org.bouncycastle.asn1.x509.qualified,\
org.bouncycastle.asn1.x509.sigi,\
org.bouncycastle.asn1.x9,\
org.bouncycastle.bcpg,\
org.bouncycastle.bcpg.attr,\
org.bouncycastle.bcpg.sig,\
org.bouncycastle.cert,\
org.bouncycastle.cert.bc,\
org.bouncycastle.cert.cmp,\
org.bouncycastle.cert.crmf,\
org.bouncycastle.cert.crmf.bc,\
org.bouncycastle.cert.crmf.jcajce,\
org.bouncycastle.cert.dane,\
org.bouncycastle.cert.dane.fetcher,\
org.bouncycastle.cert.jcajce,\
org.bouncycastle.cert.ocsp,\
org.bouncycastle.cert.ocsp.jcajce,\
org.bouncycastle.cert.path,\
org.bouncycastle.cert.path.validations,\
org.bouncycastle.cert.selector,\
org.bouncycastle.cert.selector.jcajce,\
org.bouncycastle.cmc,\
org.bouncycastle.cms,\
org.bouncycastle.cms.bc,\
org.bouncycastle.cms.jcajce,\
org.bouncycastle.crypto,\
org.bouncycastle.crypto.agreement,\
org.bouncycastle.crypto.agreement.ecjpake,\
org.bouncycastle.crypto.agreement.jpake,\
org.bouncycastle.crypto.agreement.kdf,\
org.bouncycastle.crypto.agreement.srp,\
org.bouncycastle.crypto.commitments,\
org.bouncycastle.crypto.constraints,\
org.bouncycastle.crypto.digests,\
org.bouncycastle.crypto.ec,\
org.bouncycastle.crypto.encodings,\
org.bouncycastle.crypto.engines,\
org.bouncycastle.crypto.examples,\
org.bouncycastle.crypto.fpe,\
org.bouncycastle.crypto.generators,\
org.bouncycastle.crypto.hpke,\
org.bouncycastle.crypto.io,\
org.bouncycastle.crypto.kems,\
org.bouncycastle.crypto.macs,\
org.bouncycastle.crypto.modes,\
org.bouncycastle.crypto.modes.gcm,\
org.bouncycastle.crypto.modes.kgcm,\
org.bouncycastle.crypto.paddings,\
org.bouncycastle.crypto.params,\
org.bouncycastle.crypto.parsers,\
org.bouncycastle.crypto.prng,\
org.bouncycastle.crypto.prng.drbg,\
org.bouncycastle.crypto.signers,\
org.bouncycastle.crypto.threshold,\
org.bouncycastle.crypto.tls,\
org.bouncycastle.crypto.util,\
org.bouncycastle.dvcs,\
org.bouncycastle.eac,\
org.bouncycastle.eac.jcajce,\
org.bouncycastle.eac.operator,\
org.bouncycastle.eac.operator.jcajce,\
org.bouncycastle.est,\
org.bouncycastle.est.jcajce,\
org.bouncycastle.gpg,\
org.bouncycastle.gpg.keybox,\
org.bouncycastle.gpg.keybox.bc,\
org.bouncycastle.gpg.keybox.jcajce,\
org.bouncycastle.i18n,\
org.bouncycastle.i18n.filter,\
org.bouncycastle.iana,\
org.bouncycastle.internal,\
org.bouncycastle.internal.asn1,\
org.bouncycastle.internal.asn1.bsi,\
org.bouncycastle.internal.asn1.cms,\
org.bouncycastle.internal.asn1.cryptlib,\
org.bouncycastle.internal.asn1.eac,\
org.bouncycastle.internal.asn1.edec,\
org.bouncycastle.internal.asn1.gnu,\
org.bouncycastle.internal.asn1.iana,\
org.bouncycastle.internal.asn1.isara,\
org.bouncycastle.internal.asn1.isismtt,\
org.bouncycastle.internal.asn1.iso,\
org.bouncycastle.internal.asn1.kisa,\
org.bouncycastle.internal.asn1.microsoft,\
org.bouncycastle.internal.asn1.misc,\
org.bouncycastle.internal.asn1.nsri,\
org.bouncycastle.internal.asn1.ntt,\
org.bouncycastle.internal.asn1.oiw,\
org.bouncycastle.internal.asn1.rosstandart,\
org.bouncycastle.its,\
org.bouncycastle.its.bc,\
org.bouncycastle.its.jcajce,\
org.bouncycastle.its.operator,\
org.bouncycastle.jcajce,\
org.bouncycastle.jcajce.interfaces,\
org.bouncycastle.jcajce.io,\
org.bouncycastle.jcajce.provider,\
org.bouncycastle.jcajce.provider.asymmetric,\
org.bouncycastle.jcajce.provider.asymmetric.compositesignatures,\
org.bouncycastle.jcajce.provider.asymmetric.dh,\
org.bouncycastle.jcajce.provider.asymmetric.dsa,\
org.bouncycastle.jcajce.provider.asymmetric.dstu,\
org.bouncycastle.jcajce.provider.asymmetric.ec,\
org.bouncycastle.jcajce.provider.asymmetric.ecgost,\
org.bouncycastle.jcajce.provider.asymmetric.ecgost12,\
org.bouncycastle.jcajce.provider.asymmetric.edec,\
org.bouncycastle.jcajce.provider.asymmetric.elgamal,\
org.bouncycastle.jcajce.provider.asymmetric.gost,\
org.bouncycastle.jcajce.provider.asymmetric.ies,\
org.bouncycastle.jcajce.provider.asymmetric.mldsa,\
org.bouncycastle.jcajce.provider.asymmetric.mlkem,\
org.bouncycastle.jcajce.provider.asymmetric.rsa,\
org.bouncycastle.jcajce.provider.asymmetric.slhdsa,\
org.bouncycastle.jcajce.provider.asymmetric.util,\
org.bouncycastle.jcajce.provider.asymmetric.x509,\
org.bouncycastle.jcajce.provider.config,\
org.bouncycastle.jcajce.provider.digest,\
org.bouncycastle.jcajce.provider.drbg,\
org.bouncycastle.jcajce.provider.keystore,\
org.bouncycastle.jcajce.provider.keystore.bc,\
org.bouncycastle.jcajce.provider.keystore.bcfks,\
org.bouncycastle.jcajce.provider.keystore.pkcs12,\
org.bouncycastle.jcajce.provider.keystore.util,\
org.bouncycastle.jcajce.provider.symmetric,\
org.bouncycastle.jcajce.provider.symmetric.util,\
org.bouncycastle.jcajce.provider.util,\
org.bouncycastle.jcajce.spec,\
org.bouncycastle.jcajce.util,\
org.bouncycastle.jce,\
org.bouncycastle.jce.exception,\
org.bouncycastle.jce.interfaces,\
org.bouncycastle.jce.netscape,\
org.bouncycastle.jce.provider,\
org.bouncycastle.jce.spec,\
org.bouncycastle.math,\
org.bouncycastle.math.ec,\
org.bouncycastle.math.ec.custom,\
org.bouncycastle.math.ec.custom.djb,\
org.bouncycastle.math.ec.custom.gm,\
org.bouncycastle.math.ec.custom.sec,\
org.bouncycastle.math.ec.endo,\
org.bouncycastle.math.ec.rfc7748,\
org.bouncycastle.math.ec.rfc8032,\
org.bouncycastle.math.ec.tools,\
org.bouncycastle.math.field,\
org.bouncycastle.math.raw,\
org.bouncycastle.mime,\
org.bouncycastle.mime.encoding,\
org.bouncycastle.mime.smime,\
org.bouncycastle.mozilla,\
org.bouncycastle.mozilla.jcajce,\
org.bouncycastle.oer,\
org.bouncycastle.oer.its,\
org.bouncycastle.oer.its.etsi102941,\
org.bouncycastle.oer.its.etsi102941.basetypes,\
org.bouncycastle.oer.its.etsi103097,\
org.bouncycastle.oer.its.etsi103097.extension,\
org.bouncycastle.oer.its.ieee1609dot2,\
org.bouncycastle.oer.its.ieee1609dot2.basetypes,\
org.bouncycastle.oer.its.ieee1609dot2dot1,\
org.bouncycastle.oer.its.template,\
org.bouncycastle.oer.its.template.etsi102941,\
org.bouncycastle.oer.its.template.etsi102941.basetypes,\
org.bouncycastle.oer.its.template.etsi103097,\
org.bouncycastle.oer.its.template.etsi103097.extension,\
org.bouncycastle.oer.its.template.ieee1609dot2,\
org.bouncycastle.oer.its.template.ieee1609dot2.basetypes,\
org.bouncycastle.oer.its.template.ieee1609dot2dot1,\
org.bouncycastle.openpgp,\
org.bouncycastle.openpgp.api,\
org.bouncycastle.openpgp.api.bc,\
org.bouncycastle.openpgp.api.exception,\
org.bouncycastle.openpgp.api.jcajce,\
org.bouncycastle.openpgp.api.util,\
org.bouncycastle.openpgp.bc,\
org.bouncycastle.openpgp.examples,\
org.bouncycastle.openpgp.jcajce,\
org.bouncycastle.openpgp.operator,\
org.bouncycastle.openpgp.operator.bc,\
org.bouncycastle.openpgp.operator.jcajce,\
org.bouncycastle.openssl,\
org.bouncycastle.openssl.bc,\
org.bouncycastle.openssl.jcajce,\
org.bouncycastle.operator,\
org.bouncycastle.operator.bc,\
org.bouncycastle.operator.jcajce,\
org.bouncycastle.pkcs,\
org.bouncycastle.pkcs.bc,\
org.bouncycastle.pkcs.jcajce,\
org.bouncycastle.pkix,\
org.bouncycastle.pkix.jcajce,\
org.bouncycastle.pkix.util,\
org.bouncycastle.pkix.util.filter,\
org.bouncycastle.pqc,\
org.bouncycastle.pqc.asn1,\
org.bouncycastle.pqc.crypto,\
org.bouncycastle.pqc.crypto.bike,\
org.bouncycastle.pqc.crypto.cmce,\
org.bouncycastle.pqc.crypto.crystals,\
org.bouncycastle.pqc.crypto.crystals.dilithium,\
org.bouncycastle.pqc.crypto.falcon,\
org.bouncycastle.pqc.crypto.frodo,\
org.bouncycastle.pqc.crypto.hqc,\
org.bouncycastle.pqc.crypto.lms,\
org.bouncycastle.pqc.crypto.mayo,\
org.bouncycastle.pqc.crypto.mldsa,\
org.bouncycastle.pqc.crypto.mlkem,\
org.bouncycastle.pqc.crypto.newhope,\
org.bouncycastle.pqc.crypto.ntru,\
org.bouncycastle.pqc.crypto.ntruprime,\
org.bouncycastle.pqc.crypto.picnic,\
org.bouncycastle.pqc.crypto.rainbow,\
org.bouncycastle.pqc.crypto.saber,\
org.bouncycastle.pqc.crypto.slhdsa,\
org.bouncycastle.pqc.crypto.snova,\
org.bouncycastle.pqc.crypto.sphincs,\
org.bouncycastle.pqc.crypto.sphincsplus,\
org.bouncycastle.pqc.crypto.util,\
org.bouncycastle.pqc.crypto.xmss,\
org.bouncycastle.pqc.crypto.xwing,\
org.bouncycastle.pqc.jcajce,\
org.bouncycastle.pqc.jcajce.interfaces,\
org.bouncycastle.pqc.jcajce.provider,\
org.bouncycastle.pqc.jcajce.provider.bike,\
org.bouncycastle.pqc.jcajce.provider.cmce,\
org.bouncycastle.pqc.jcajce.provider.dilithium,\
org.bouncycastle.pqc.jcajce.provider.falcon,\
org.bouncycastle.pqc.jcajce.provider.frodo,\
org.bouncycastle.pqc.jcajce.provider.hqc,\
org.bouncycastle.pqc.jcajce.provider.kyber,\
org.bouncycastle.pqc.jcajce.provider.lms,\
org.bouncycastle.pqc.jcajce.provider.mayo,\
org.bouncycastle.pqc.jcajce.provider.newhope,\
org.bouncycastle.pqc.jcajce.provider.ntru,\
org.bouncycastle.pqc.jcajce.provider.ntruprime,\
org.bouncycastle.pqc.jcajce.provider.picnic,\
org.bouncycastle.pqc.jcajce.provider.saber,\
org.bouncycastle.pqc.jcajce.provider.snova,\
org.bouncycastle.pqc.jcajce.provider.sphincs,\
org.bouncycastle.pqc.jcajce.provider.sphincsplus,\
org.bouncycastle.pqc.jcajce.provider.util,\
org.bouncycastle.pqc.jcajce.provider.xmss,\
org.bouncycastle.pqc.jcajce.spec,\
org.bouncycastle.pqc.math,\
org.bouncycastle.pqc.math.ntru,\
org.bouncycastle.pqc.math.ntru.parameters,\
org.bouncycastle.tsp,\
org.bouncycastle.tsp.cms,\
org.bouncycastle.tsp.ers,\
org.bouncycastle.util,\
org.bouncycastle.util.encoders,\
org.bouncycastle.util.io,\
org.bouncycastle.util.io.pem,\
org.bouncycastle.util.test,\
org.bouncycastle.voms,\
org.bouncycastle.x509,\
org.bouncycastle.x509.extension,\
org.bouncycastle.x509.util,\
org.eclipse,\
org.eclipse.jdt,\
org.eclipse.jdt.core,\
org.eclipse.jdt.core.compiler,\
org.eclipse.jdt.core.compiler.batch,\
org.eclipse.jdt.internal,\
org.eclipse.jdt.internal.antadapter,\
org.eclipse.jdt.internal.compiler,\
org.eclipse.jdt.internal.compiler.apt,\
org.eclipse.jdt.internal.compiler.apt.dispatch,\
org.eclipse.jdt.internal.compiler.apt.model,\
org.eclipse.jdt.internal.compiler.apt.util,\
org.eclipse.jdt.internal.compiler.ast,\
org.eclipse.jdt.internal.compiler.batch,\
org.eclipse.jdt.internal.compiler.classfmt,\
org.eclipse.jdt.internal.compiler.codegen,\
org.eclipse.jdt.internal.compiler.env,\
org.eclipse.jdt.internal.compiler.flow,\
org.eclipse.jdt.internal.compiler.impl,\
org.eclipse.jdt.internal.compiler.lookup,\
org.eclipse.jdt.internal.compiler.parser,\
org.eclipse.jdt.internal.compiler.parser.diagnose,\
org.eclipse.jdt.internal.compiler.parser.unicode,\
org.eclipse.jdt.internal.compiler.parser.unicode10,\
org.eclipse.jdt.internal.compiler.parser.unicode11,\
org.eclipse.jdt.internal.compiler.parser.unicode12_1,\
org.eclipse.jdt.internal.compiler.parser.unicode13,\
org.eclipse.jdt.internal.compiler.parser.unicode6,\
org.eclipse.jdt.internal.compiler.parser.unicode6_2,\
org.eclipse.jdt.internal.compiler.parser.unicode7,\
org.eclipse.jdt.internal.compiler.parser.unicode8,\
org.eclipse.jdt.internal.compiler.problem,\
org.eclipse.jdt.internal.compiler.tool,\
org.eclipse.jdt.internal.compiler.util,\
org.eclipse.jgit,\
org.eclipse.jgit.annotations,\
org.eclipse.jgit.api,\
org.eclipse.jgit.api.errors,\
org.eclipse.jgit.attributes,\
org.eclipse.jgit.blame,\
org.eclipse.jgit.blame.cache,\
org.eclipse.jgit.diff,\
org.eclipse.jgit.dircache,\
org.eclipse.jgit.errors,\
org.eclipse.jgit.events,\
org.eclipse.jgit.fnmatch,\
org.eclipse.jgit.gitrepo,\
org.eclipse.jgit.gitrepo.internal,\
org.eclipse.jgit.hooks,\
org.eclipse.jgit.ignore,\
org.eclipse.jgit.ignore.internal,\
org.eclipse.jgit.internal,\
org.eclipse.jgit.internal.diff,\
org.eclipse.jgit.internal.diffmergetool,\
org.eclipse.jgit.internal.fsck,\
org.eclipse.jgit.internal.revwalk,\
org.eclipse.jgit.internal.signing,\
org.eclipse.jgit.internal.signing.ssh,\
org.eclipse.jgit.internal.storage,\
org.eclipse.jgit.internal.storage.commitgraph,\
org.eclipse.jgit.internal.storage.dfs,\
org.eclipse.jgit.internal.storage.file,\
org.eclipse.jgit.internal.storage.io,\
org.eclipse.jgit.internal.storage.memory,\
org.eclipse.jgit.internal.storage.midx,\
org.eclipse.jgit.internal.storage.pack,\
org.eclipse.jgit.internal.storage.reftable,\
org.eclipse.jgit.internal.submodule,\
org.eclipse.jgit.internal.transport,\
org.eclipse.jgit.internal.transport.connectivity,\
org.eclipse.jgit.internal.transport.http,\
org.eclipse.jgit.internal.transport.parser,\
org.eclipse.jgit.internal.transport.ssh,\
org.eclipse.jgit.internal.transport.sshd,\
org.eclipse.jgit.internal.transport.sshd.agent,\
org.eclipse.jgit.internal.transport.sshd.auth,\
org.eclipse.jgit.internal.transport.sshd.pkcs11,\
org.eclipse.jgit.internal.transport.sshd.proxy,\
org.eclipse.jgit.internal.util,\
org.eclipse.jgit.lib,\
org.eclipse.jgit.lib.internal,\
org.eclipse.jgit.logging,\
org.eclipse.jgit.merge,\
org.eclipse.jgit.nls,\
org.eclipse.jgit.notes,\
org.eclipse.jgit.patch,\
org.eclipse.jgit.revplot,\
org.eclipse.jgit.revwalk,\
org.eclipse.jgit.revwalk.filter,\
org.eclipse.jgit.signing,\
org.eclipse.jgit.signing.ssh,\
org.eclipse.jgit.storage,\
org.eclipse.jgit.storage.file,\
org.eclipse.jgit.storage.pack,\
org.eclipse.jgit.submodule,\
org.eclipse.jgit.transport,\
org.eclipse.jgit.transport.http,\
org.eclipse.jgit.transport.resolver,\
org.eclipse.jgit.transport.sshd,\
org.eclipse.jgit.transport.sshd.agent,\
org.eclipse.jgit.treewalk,\
org.eclipse.jgit.treewalk.filter,\
org.eclipse.jgit.util,\
org.eclipse.jgit.util.io,\
org.eclipse.jgit.util.sha1,\
org.eclipse.jgit.util.time,\
org.eclipse.parsson,\
org.eclipse.parsson.api,\
org.eclipse.tags,\
org.eclipse.tags.shaded,\
org.eclipse.tags.shaded.java_cup,\
org.eclipse.tags.shaded.java_cup.runtime,\
org.eclipse.tags.shaded.org,\
org.eclipse.tags.shaded.org.apache,\
org.eclipse.tags.shaded.org.apache.bcel,\
org.eclipse.tags.shaded.org.apache.bcel.classfile,\
org.eclipse.tags.shaded.org.apache.bcel.generic,\
org.eclipse.tags.shaded.org.apache.bcel.util,\
org.eclipse.tags.shaded.org.apache.bcel.verifier,\
org.eclipse.tags.shaded.org.apache.bcel.verifier.exc,\
org.eclipse.tags.shaded.org.apache.bcel.verifier.statics,\
org.eclipse.tags.shaded.org.apache.bcel.verifier.structurals,\
org.eclipse.tags.shaded.org.apache.regexp,\
org.eclipse.tags.shaded.org.apache.xalan,\
org.eclipse.tags.shaded.org.apache.xalan.client,\
org.eclipse.tags.shaded.org.apache.xalan.extensions,\
org.eclipse.tags.shaded.org.apache.xalan.lib,\
org.eclipse.tags.shaded.org.apache.xalan.lib.sql,\
org.eclipse.tags.shaded.org.apache.xalan.processor,\
org.eclipse.tags.shaded.org.apache.xalan.res,\
org.eclipse.tags.shaded.org.apache.xalan.serialize,\
org.eclipse.tags.shaded.org.apache.xalan.templates,\
org.eclipse.tags.shaded.org.apache.xalan.trace,\
org.eclipse.tags.shaded.org.apache.xalan.transformer,\
org.eclipse.tags.shaded.org.apache.xalan.xslt,\
org.eclipse.tags.shaded.org.apache.xalan.xslt.util,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.cmdline,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.cmdline.getopt,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.compiler,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.compiler.util,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.dom,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.runtime,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.runtime.output,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.trax,\
org.eclipse.tags.shaded.org.apache.xalan.xsltc.util,\
org.eclipse.tags.shaded.org.apache.xml,\
org.eclipse.tags.shaded.org.apache.xml.dtm,\
org.eclipse.tags.shaded.org.apache.xml.dtm.ref,\
org.eclipse.tags.shaded.org.apache.xml.dtm.ref.dom2dtm,\
org.eclipse.tags.shaded.org.apache.xml.dtm.ref.sax2dtm,\
org.eclipse.tags.shaded.org.apache.xml.res,\
org.eclipse.tags.shaded.org.apache.xml.utils,\
org.eclipse.tags.shaded.org.apache.xml.utils.res,\
org.eclipse.tags.shaded.org.apache.xpath,\
org.eclipse.tags.shaded.org.apache.xpath.axes,\
org.eclipse.tags.shaded.org.apache.xpath.compiler,\
org.eclipse.tags.shaded.org.apache.xpath.domapi,\
org.eclipse.tags.shaded.org.apache.xpath.functions,\
org.eclipse.tags.shaded.org.apache.xpath.jaxp,\
org.eclipse.tags.shaded.org.apache.xpath.objects,\
org.eclipse.tags.shaded.org.apache.xpath.operations,\
org.eclipse.tags.shaded.org.apache.xpath.patterns,\
org.eclipse.tags.shaded.org.apache.xpath.res,\
org.eclipse.tags.shaded.trax,\
org.eclipse.yasson,\
org.eclipse.yasson.internal,\
org.eclipse.yasson.internal.components,\
org.eclipse.yasson.internal.deserializer,\
org.eclipse.yasson.internal.deserializer.types,\
org.eclipse.yasson.internal.jsonstructure,\
org.eclipse.yasson.internal.model,\
org.eclipse.yasson.internal.model.customization,\
org.eclipse.yasson.internal.properties,\
org.eclipse.yasson.internal.serializer,\
org.eclipse.yasson.internal.serializer.types,\
org.eclipse.yasson.spi,\
org.fusesource,\
org.fusesource.hawtjni,\
org.fusesource.hawtjni.runtime,\
org.fusesource.jansi,\
org.fusesource.jansi.internal,\
org.glassfish,\
org.glassfish.enterprise,\
org.glassfish.enterprise.concurrent,\
org.glassfish.enterprise.concurrent.cdi,\
org.glassfish.enterprise.concurrent.internal,\
org.glassfish.enterprise.concurrent.spi,\
org.glassfish.expressly,\
org.glassfish.expressly.lang,\
org.glassfish.expressly.parser,\
org.glassfish.expressly.stream,\
org.glassfish.expressly.util,\
org.glassfish.json,\
org.glassfish.json.api,\
org.infinispan,\
org.infinispan.commons,\
org.infinispan.commons.api,\
org.infinispan.commons.api.multimap,\
org.infinispan.commons.api.query,\
org.infinispan.commons.api.query.geo,\
org.infinispan.commons.api.query.impl,\
org.infinispan.commons.configuration,\
org.infinispan.commons.configuration.attributes,\
org.infinispan.commons.configuration.io,\
org.infinispan.commons.configuration.io.json,\
org.infinispan.commons.configuration.io.xml,\
org.infinispan.commons.configuration.io.yaml,\
org.infinispan.commons.dataconversion,\
org.infinispan.commons.dataconversion.internal,\
org.infinispan.commons.executors,\
org.infinispan.commons.hash,\
org.infinispan.commons.internal,\
org.infinispan.commons.io,\
org.infinispan.commons.jdkspecific,\
org.infinispan.commons.jmx,\
org.infinispan.commons.logging,\
org.infinispan.commons.logging.log4j,\
org.infinispan.commons.marshall,\
org.infinispan.commons.marshall.exts,\
org.infinispan.commons.maven,\
org.infinispan.commons.persistence,\
org.infinispan.commons.reactive,\
org.infinispan.commons.spi,\
org.infinispan.commons.stat,\
org.infinispan.commons.stat.micrometer,\
org.infinispan.commons.time,\
org.infinispan.commons.tx,\
org.infinispan.commons.tx.lookup,\
org.infinispan.commons.util,\
org.infinispan.commons.util.concurrent,\
org.infinispan.commons.util.logging,\
org.infinispan.protostream,\
org.infinispan.protostream.annotations,\
org.infinispan.protostream.annotations.impl,\
org.infinispan.protostream.annotations.impl.types,\
org.infinispan.protostream.config,\
org.infinispan.protostream.config.impl,\
org.infinispan.protostream.containers,\
org.infinispan.protostream.descriptors,\
org.infinispan.protostream.descriptors.namespace,\
org.infinispan.protostream.exception,\
org.infinispan.protostream.impl,\
org.infinispan.protostream.impl.parser,\
org.infinispan.protostream.schema,\
org.jboss,\
org.jboss.annotation,\
org.jboss.annotation.javaee,\
org.jboss.as,\
org.jboss.as.cli,\
org.jboss.as.cli.accesscontrol,\
org.jboss.as.cli.batch,\
org.jboss.as.cli.batch.impl,\
org.jboss.as.cli.embedded,\
org.jboss.as.cli.gui,\
org.jboss.as.cli.gui.component,\
org.jboss.as.cli.gui.metacommand,\
org.jboss.as.cli.handlers,\
org.jboss.as.cli.handlers.batch,\
org.jboss.as.cli.handlers.ifelse,\
org.jboss.as.cli.handlers.jca,\
org.jboss.as.cli.handlers.loop,\
org.jboss.as.cli.handlers.module,\
org.jboss.as.cli.handlers.report,\
org.jboss.as.cli.handlers.trycatch,\
org.jboss.as.cli.impl,\
org.jboss.as.cli.impl._private,\
org.jboss.as.cli.impl.aesh,\
org.jboss.as.cli.impl.aesh.cmd,\
org.jboss.as.cli.impl.aesh.cmd.deployment,\
org.jboss.as.cli.impl.aesh.cmd.deployment.security,\
org.jboss.as.cli.impl.aesh.cmd.operation,\
org.jboss.as.cli.impl.aesh.cmd.security,\
org.jboss.as.cli.impl.aesh.cmd.security.auth,\
org.jboss.as.cli.impl.aesh.cmd.security.model,\
org.jboss.as.cli.impl.aesh.cmd.security.ssl,\
org.jboss.as.cli.operation,\
org.jboss.as.cli.operation.impl,\
org.jboss.as.cli.parsing,\
org.jboss.as.cli.parsing.arguments,\
org.jboss.as.cli.parsing.command,\
org.jboss.as.cli.parsing.operation,\
org.jboss.as.cli.parsing.operation.header,\
org.jboss.as.cli.scriptsupport,\
org.jboss.as.cli.util,\
org.jboss.as.clustering,\
org.jboss.as.clustering.controller,\
org.jboss.as.clustering.controller.descriptions,\
org.jboss.as.clustering.controller.transform,\
org.jboss.as.clustering.controller.validation,\
org.jboss.as.clustering.logging,\
org.jboss.as.clustering.msc,\
org.jboss.as.clustering.naming,\
org.jboss.as.clustering.service,\
org.jboss.as.controller,\
org.jboss.as.controller._private,\
org.jboss.as.controller.access,\
org.jboss.as.controller.access.constraint,\
org.jboss.as.controller.access.management,\
org.jboss.as.controller.access.permission,\
org.jboss.as.controller.access.rbac,\
org.jboss.as.controller.audit,\
org.jboss.as.controller.capability,\
org.jboss.as.controller.capability.registry,\
org.jboss.as.controller.client,\
org.jboss.as.controller.client.helpers,\
org.jboss.as.controller.client.helpers.domain,\
org.jboss.as.controller.client.helpers.domain.impl,\
org.jboss.as.controller.client.helpers.standalone,\
org.jboss.as.controller.client.helpers.standalone.impl,\
org.jboss.as.controller.client.impl,\
org.jboss.as.controller.client.logging,\
org.jboss.as.controller.descriptions,\
org.jboss.as.controller.descriptions.common,\
org.jboss.as.controller.extension,\
org.jboss.as.controller.interfaces,\
org.jboss.as.controller.logging,\
org.jboss.as.controller.management,\
org.jboss.as.controller.notification,\
org.jboss.as.controller.operations,\
org.jboss.as.controller.operations.common,\
org.jboss.as.controller.operations.global,\
org.jboss.as.controller.operations.validation,\
org.jboss.as.controller.parsing,\
org.jboss.as.controller.persistence,\
org.jboss.as.controller.persistence.xml,\
org.jboss.as.controller.persistence.yaml,\
org.jboss.as.controller.registry,\
org.jboss.as.controller.remote,\
org.jboss.as.controller.resource,\
org.jboss.as.controller.security,\
org.jboss.as.controller.services,\
org.jboss.as.controller.services.path,\
org.jboss.as.controller.transform,\
org.jboss.as.controller.transform.description,\
org.jboss.as.controller.xml,\
org.jboss.as.core,\
org.jboss.as.core.security,\
org.jboss.as.domain,\
org.jboss.as.domain.controller,\
org.jboss.as.domain.controller.logging,\
org.jboss.as.domain.controller.operations,\
org.jboss.as.domain.controller.operations.coordination,\
org.jboss.as.domain.controller.operations.deployment,\
org.jboss.as.domain.controller.plan,\
org.jboss.as.domain.controller.resources,\
org.jboss.as.domain.controller.transformers,\
org.jboss.as.domain.http,\
org.jboss.as.domain.http.server,\
org.jboss.as.domain.http.server.cors,\
org.jboss.as.domain.http.server.logging,\
org.jboss.as.domain.http.server.security,\
org.jboss.as.domain.management,\
org.jboss.as.domain.management._private,\
org.jboss.as.domain.management.access,\
org.jboss.as.domain.management.audit,\
org.jboss.as.domain.management.audit.validators,\
org.jboss.as.domain.management.controller,\
org.jboss.as.domain.management.logging,\
org.jboss.as.domain.management.parsing,\
org.jboss.as.domain.management.security,\
org.jboss.as.domain.management.security.adduser,\
org.jboss.as.domain.management.security.password,\
org.jboss.as.domain.management.security.password.simple,\
org.jboss.as.ee,\
org.jboss.as.ee.component,\
org.jboss.as.ee.component.deployers,\
org.jboss.as.ee.component.interceptors,\
org.jboss.as.ee.component.serialization,\
org.jboss.as.ee.concurrent,\
org.jboss.as.ee.concurrent.adapter,\
org.jboss.as.ee.concurrent.deployers,\
org.jboss.as.ee.concurrent.deployers.injection,\
org.jboss.as.ee.concurrent.handle,\
org.jboss.as.ee.concurrent.resource,\
org.jboss.as.ee.concurrent.resource.definition,\
org.jboss.as.ee.concurrent.service,\
org.jboss.as.ee.logging,\
org.jboss.as.ee.managedbean,\
org.jboss.as.ee.managedbean.component,\
org.jboss.as.ee.managedbean.processors,\
org.jboss.as.ee.metadata,\
org.jboss.as.ee.metadata.property,\
org.jboss.as.ee.naming,\
org.jboss.as.ee.resource,\
org.jboss.as.ee.resource.definition,\
org.jboss.as.ee.security,\
org.jboss.as.ee.structure,\
org.jboss.as.ee.subsystem,\
org.jboss.as.ee.utils,\
org.jboss.as.ee.weld,\
org.jboss.as.host,\
org.jboss.as.host.controller,\
org.jboss.as.host.controller.descriptions,\
org.jboss.as.host.controller.discovery,\
org.jboss.as.host.controller.embedded,\
org.jboss.as.host.controller.ignored,\
org.jboss.as.host.controller.jvm,\
org.jboss.as.host.controller.logging,\
org.jboss.as.host.controller.mgmt,\
org.jboss.as.host.controller.model,\
org.jboss.as.host.controller.model.host,\
org.jboss.as.host.controller.model.jvm,\
org.jboss.as.host.controller.operations,\
org.jboss.as.host.controller.parsing,\
org.jboss.as.host.controller.resources,\
org.jboss.as.host.controller.security,\
org.jboss.as.jmx,\
org.jboss.as.jmx.logging,\
org.jboss.as.jmx.model,\
org.jboss.as.logging,\
org.jboss.as.logging.capabilities,\
org.jboss.as.logging.correctors,\
org.jboss.as.logging.deployments,\
org.jboss.as.logging.deployments.resources,\
org.jboss.as.logging.filters,\
org.jboss.as.logging.formatters,\
org.jboss.as.logging.handlers,\
org.jboss.as.logging.loggers,\
org.jboss.as.logging.logging,\
org.jboss.as.logging.logmanager,\
org.jboss.as.logging.resolvers,\
org.jboss.as.logging.stdio,\
org.jboss.as.logging.validators,\
org.jboss.as.management,\
org.jboss.as.management.client,\
org.jboss.as.management.client.content,\
org.jboss.as.naming,\
org.jboss.as.naming.context,\
org.jboss.as.naming.context.external,\
org.jboss.as.naming.deployment,\
org.jboss.as.naming.interfaces,\
org.jboss.as.naming.interfaces.java,\
org.jboss.as.naming.logging,\
org.jboss.as.naming.management,\
org.jboss.as.naming.remote,\
org.jboss.as.naming.service,\
org.jboss.as.naming.subsystem,\
org.jboss.as.naming.util,\
org.jboss.as.network,\
org.jboss.as.network.logging,\
org.jboss.as.platform,\
org.jboss.as.platform.mbean,\
org.jboss.as.platform.mbean.logging,\
org.jboss.as.process,\
org.jboss.as.process.logging,\
org.jboss.as.process.protocol,\
org.jboss.as.process.stdin,\
org.jboss.as.protocol,\
org.jboss.as.protocol.logging,\
org.jboss.as.protocol.mgmt,\
org.jboss.as.protocol.mgmt.support,\
org.jboss.as.quickstart,\
org.jboss.as.quickstart.http_custom_mechanism,\
org.jboss.as.remoting,\
org.jboss.as.remoting.logging,\
org.jboss.as.remoting.management,\
org.jboss.as.repository,\
org.jboss.as.repository.logging,\
org.jboss.as.server,\
org.jboss.as.server.controller,\
org.jboss.as.server.controller.descriptions,\
org.jboss.as.server.controller.git,\
org.jboss.as.server.controller.resources,\
org.jboss.as.server.deployment,\
org.jboss.as.server.deployment.annotation,\
org.jboss.as.server.deployment.client,\
org.jboss.as.server.deployment.dependencies,\
org.jboss.as.server.deployment.jbossallxml,\
org.jboss.as.server.deployment.module,\
org.jboss.as.server.deployment.module.descriptor,\
org.jboss.as.server.deployment.reflect,\
org.jboss.as.server.deployment.scanner,\
org.jboss.as.server.deployment.scanner.api,\
org.jboss.as.server.deployment.scanner.logging,\
org.jboss.as.server.deployment.service,\
org.jboss.as.server.deployment.transformation,\
org.jboss.as.server.deploymentoverlay,\
org.jboss.as.server.embedded,\
org.jboss.as.server.jmx,\
org.jboss.as.server.logging,\
org.jboss.as.server.mgmt,\
org.jboss.as.server.mgmt.domain,\
org.jboss.as.server.moduleservice,\
org.jboss.as.server.operations,\
org.jboss.as.server.parsing,\
org.jboss.as.server.security,\
org.jboss.as.server.security.sasl,\
org.jboss.as.server.services,\
org.jboss.as.server.services.net,\
org.jboss.as.server.suspend,\
org.jboss.as.version,\
org.jboss.as.web,\
org.jboss.as.web.common,\
org.jboss.as.web.host,\
org.jboss.as.web.session,\
org.jboss.classfilewriter,\
org.jboss.classfilewriter.annotations,\
org.jboss.classfilewriter.attributes,\
org.jboss.classfilewriter.code,\
org.jboss.classfilewriter.constpool,\
org.jboss.classfilewriter.util,\
org.jboss.common,\
org.jboss.common.beans,\
org.jboss.common.beans.property,\
org.jboss.common.beans.property.finder,\
org.jboss.common.beans.property.token,\
org.jboss.dmr,\
org.jboss.dmr._private,\
org.jboss.dmr.stream,\
org.jboss.ejb,\
org.jboss.ejb._private,\
org.jboss.ejb.client,\
org.jboss.ejb.client.annotation,\
org.jboss.ejb.client.legacy,\
org.jboss.ejb.client.naming,\
org.jboss.ejb.client.naming.ejb,\
org.jboss.ejb.protocol,\
org.jboss.ejb.protocol.remote,\
org.jboss.ejb.server,\
org.jboss.el,\
org.jboss.el.cache,\
org.jboss.invocation,\
org.jboss.invocation.proxy,\
org.jboss.invocation.proxy.classloading,\
org.jboss.invocation.proxy.reflection,\
org.jboss.jandex,\
org.jboss.logging,\
org.jboss.logmanager,\
org.jboss.logmanager.config,\
org.jboss.logmanager.errormanager,\
org.jboss.logmanager.filters,\
org.jboss.logmanager.formatters,\
org.jboss.logmanager.handlers,\
org.jboss.logmanager.log4j,\
org.jboss.marshalling,\
org.jboss.marshalling._private,\
org.jboss.marshalling.cloner,\
org.jboss.marshalling.reflect,\
org.jboss.marshalling.river,\
org.jboss.marshalling.util,\
org.jboss.metadata,\
org.jboss.metadata.annotation,\
org.jboss.metadata.common,\
org.jboss.metadata.common.ejb,\
org.jboss.metadata.common.jboss,\
org.jboss.metadata.ear,\
org.jboss.metadata.ear.jboss,\
org.jboss.metadata.ear.merge,\
org.jboss.metadata.ear.parser,\
org.jboss.metadata.ear.parser.jboss,\
org.jboss.metadata.ear.parser.spec,\
org.jboss.metadata.ear.spec,\
org.jboss.metadata.javaee,\
org.jboss.metadata.javaee.jboss,\
org.jboss.metadata.javaee.spec,\
org.jboss.metadata.javaee.support,\
org.jboss.metadata.merge,\
org.jboss.metadata.merge.ejb,\
org.jboss.metadata.merge.ejb.jboss,\
org.jboss.metadata.merge.javaee,\
org.jboss.metadata.merge.javaee.jboss,\
org.jboss.metadata.merge.javaee.spec,\
org.jboss.metadata.merge.javaee.support,\
org.jboss.metadata.merge.web,\
org.jboss.metadata.merge.web.jboss,\
org.jboss.metadata.merge.web.spec,\
org.jboss.metadata.parser,\
org.jboss.metadata.parser.ee,\
org.jboss.metadata.parser.jbossee,\
org.jboss.metadata.parser.jbossweb,\
org.jboss.metadata.parser.jsp,\
org.jboss.metadata.parser.servlet,\
org.jboss.metadata.parser.util,\
org.jboss.metadata.property,\
org.jboss.metadata.web,\
org.jboss.metadata.web.jboss,\
org.jboss.metadata.web.spec,\
org.jboss.msc,\
org.jboss.msc.inject,\
org.jboss.msc.service,\
org.jboss.msc.service.management,\
org.jboss.msc.value,\
org.jboss.remoting3,\
org.jboss.remoting3._private,\
org.jboss.remoting3.remote,\
org.jboss.remoting3.security,\
org.jboss.remoting3.spi,\
org.jboss.remoting3.util,\
org.jboss.staxmapper,\
org.jboss.stdio,\
org.jboss.threads,\
org.jboss.threads.management,\
org.jboss.tm,\
org.jboss.tm.listener,\
org.jboss.tm.usertx,\
org.jboss.tm.usertx.client,\
org.jboss.vfs,\
org.jboss.vfs.protocol,\
org.jboss.vfs.protocol.file,\
org.jboss.vfs.protocol.vfs,\
org.jboss.vfs.spi,\
org.jboss.vfs.util,\
org.jboss.vfs.util.automount,\
org.projectodd,\
org.projectodd.vdx,\
org.projectodd.vdx.core,\
org.projectodd.vdx.core.handlers,\
org.projectodd.vdx.core.schema,\
org.projectodd.vdx.core.thirdparty,\
org.projectodd.vdx.wildfly,\
org.reactivestreams,\
org.slf4j,\
org.slf4j.bridge,\
org.slf4j.event,\
org.slf4j.helpers,\
org.slf4j.impl,\
org.slf4j.spi,\
org.wildfly,\
org.wildfly.client,\
org.wildfly.client.config,\
org.wildfly.client.config._private,\
org.wildfly.clustering,\
org.wildfly.clustering.cache,\
org.wildfly.clustering.cache.batch,\
org.wildfly.clustering.cache.function,\
org.wildfly.clustering.cache.infinispan,\
org.wildfly.clustering.cache.infinispan.batch,\
org.wildfly.clustering.cache.infinispan.marshalling,\
org.wildfly.clustering.context,\
org.wildfly.clustering.dispatcher,\
org.wildfly.clustering.function,\
org.wildfly.clustering.group,\
org.wildfly.clustering.marshalling,\
org.wildfly.clustering.marshalling.protostream,\
org.wildfly.clustering.marshalling.protostream.math,\
org.wildfly.clustering.marshalling.protostream.modules,\
org.wildfly.clustering.marshalling.protostream.net,\
org.wildfly.clustering.marshalling.protostream.reflect,\
org.wildfly.clustering.marshalling.protostream.sql,\
org.wildfly.clustering.marshalling.protostream.time,\
org.wildfly.clustering.marshalling.protostream.util,\
org.wildfly.clustering.marshalling.protostream.util.concurrent,\
org.wildfly.clustering.marshalling.protostream.util.concurrent.atomic,\
org.wildfly.clustering.marshalling.util,\
org.wildfly.clustering.provider,\
org.wildfly.clustering.registry,\
org.wildfly.clustering.server,\
org.wildfly.clustering.server.cache,\
org.wildfly.clustering.server.deployment,\
org.wildfly.clustering.server.dispatcher,\
org.wildfly.clustering.server.eviction,\
org.wildfly.clustering.server.expiration,\
org.wildfly.clustering.server.group,\
org.wildfly.clustering.server.immutable,\
org.wildfly.clustering.server.listener,\
org.wildfly.clustering.server.manager,\
org.wildfly.clustering.server.offset,\
org.wildfly.clustering.server.provider,\
org.wildfly.clustering.server.registry,\
org.wildfly.clustering.server.scheduler,\
org.wildfly.clustering.server.service,\
org.wildfly.clustering.server.util,\
org.wildfly.clustering.service,\
org.wildfly.clustering.service.concurrent,\
org.wildfly.clustering.web,\
org.wildfly.clustering.web.container,\
org.wildfly.common,\
org.wildfly.common._private,\
org.wildfly.common.annotation,\
org.wildfly.common.archive,\
org.wildfly.common.array,\
org.wildfly.common.bytes,\
org.wildfly.common.codec,\
org.wildfly.common.context,\
org.wildfly.common.cpu,\
org.wildfly.common.expression,\
org.wildfly.common.flags,\
org.wildfly.common.function,\
org.wildfly.common.iteration,\
org.wildfly.common.lock,\
org.wildfly.common.math,\
org.wildfly.common.net,\
org.wildfly.common.os,\
org.wildfly.common.ref,\
org.wildfly.common.rpc,\
org.wildfly.common.selector,\
org.wildfly.common.string,\
org.wildfly.common.xml,\
org.wildfly.core,\
org.wildfly.core.cli,\
org.wildfly.core.cli.command,\
org.wildfly.core.cli.command.aesh,\
org.wildfly.core.cli.command.aesh.activator,\
org.wildfly.core.embedded,\
org.wildfly.core.embedded.logging,\
org.wildfly.core.embedded.spi,\
org.wildfly.core.instmgr,\
org.wildfly.core.instmgr.cli,\
org.wildfly.core.instmgr.logging,\
org.wildfly.core.jar,\
org.wildfly.core.jar.runtime,\
org.wildfly.core.jar.runtime._private,\
org.wildfly.discovery,\
org.wildfly.discovery.impl,\
org.wildfly.discovery.spi,\
org.wildfly.elytron,\
org.wildfly.elytron.web,\
org.wildfly.elytron.web.undertow,\
org.wildfly.elytron.web.undertow.server,\
org.wildfly.elytron.web.undertow.server.servlet,\
org.wildfly.elytron.web.undertow.server.sni,\
org.wildfly.event,\
org.wildfly.event.logger,\
org.wildfly.extension,\
org.wildfly.extension.core,\
org.wildfly.extension.core.management,\
org.wildfly.extension.core.management.client,\
org.wildfly.extension.elytron,\
org.wildfly.extension.elytron._private,\
org.wildfly.extension.elytron.capabilities,\
org.wildfly.extension.elytron.capabilities._private,\
org.wildfly.extension.elytron.expression,\
org.wildfly.extension.io,\
org.wildfly.extension.io.logging,\
org.wildfly.extension.requestcontroller,\
org.wildfly.extension.requestcontroller.logging,\
org.wildfly.extension.undertow,\
org.wildfly.extension.undertow.deployment,\
org.wildfly.extension.undertow.filters,\
org.wildfly.extension.undertow.handlers,\
org.wildfly.extension.undertow.logging,\
org.wildfly.extension.undertow.security,\
org.wildfly.extension.undertow.security.jacc,\
org.wildfly.extension.undertow.session,\
org.wildfly.extension.undertow.sso,\
org.wildfly.extension.undertow.sso.elytron,\
org.wildfly.httpclient,\
org.wildfly.httpclient.common,\
org.wildfly.httpclient.naming,\
org.wildfly.installationmanager,\
org.wildfly.installationmanager.spi,\
org.wildfly.io,\
org.wildfly.naming,\
org.wildfly.naming.client,\
org.wildfly.naming.client._private,\
org.wildfly.naming.client.remote,\
org.wildfly.naming.client.store,\
org.wildfly.naming.client.util,\
org.wildfly.naming.java,\
org.wildfly.naming.java.permission,\
org.wildfly.naming.security,\
org.wildfly.openssl,\
org.wildfly.openssl.util,\
org.wildfly.security,\
org.wildfly.security.asn1,\
org.wildfly.security.audit,\
org.wildfly.security.auth,\
org.wildfly.security.auth.callback,\
org.wildfly.security.auth.client,\
org.wildfly.security.auth.client._private,\
org.wildfly.security.auth.jaspi,\
org.wildfly.security.auth.jaspi._private,\
org.wildfly.security.auth.jaspi.impl,\
org.wildfly.security.auth.permission,\
org.wildfly.security.auth.principal,\
org.wildfly.security.auth.realm,\
org.wildfly.security.auth.realm.jdbc,\
org.wildfly.security.auth.realm.jdbc._private,\
org.wildfly.security.auth.realm.jdbc.mapper,\
org.wildfly.security.auth.realm.ldap,\
org.wildfly.security.auth.realm.token,\
org.wildfly.security.auth.realm.token._private,\
org.wildfly.security.auth.realm.token.validator,\
org.wildfly.security.auth.server,\
org.wildfly.security.auth.server._private,\
org.wildfly.security.auth.server.event,\
org.wildfly.security.auth.server.http,\
org.wildfly.security.auth.server.sasl,\
org.wildfly.security.auth.util,\
org.wildfly.security.authz,\
org.wildfly.security.authz.jacc,\
org.wildfly.security.cache,\
org.wildfly.security.credential,\
org.wildfly.security.credential._private,\
org.wildfly.security.credential.source,\
org.wildfly.security.credential.source.impl,\
org.wildfly.security.credential.store,\
org.wildfly.security.credential.store._private,\
org.wildfly.security.credential.store.impl,\
org.wildfly.security.digest,\
org.wildfly.security.dynamic,\
org.wildfly.security.dynamic.ssl,\
org.wildfly.security.encryption,\
org.wildfly.security.evidence,\
org.wildfly.security.http,\
org.wildfly.security.http.basic,\
org.wildfly.security.http.bearer,\
org.wildfly.security.http.cert,\
org.wildfly.security.http.digest,\
org.wildfly.security.http.external,\
org.wildfly.security.http.form,\
org.wildfly.security.http.impl,\
org.wildfly.security.http.spnego,\
org.wildfly.security.http.util,\
org.wildfly.security.http.util.sso,\
org.wildfly.security.jakarta,\
org.wildfly.security.jakarta.authz,\
org.wildfly.security.json,\
org.wildfly.security.json.util,\
org.wildfly.security.key,\
org.wildfly.security.keystore,\
org.wildfly.security.manager,\
org.wildfly.security.manager._private,\
org.wildfly.security.manager.action,\
org.wildfly.security.mechanism,\
org.wildfly.security.mechanism._private,\
org.wildfly.security.mechanism.digest,\
org.wildfly.security.mechanism.gssapi,\
org.wildfly.security.mechanism.http,\
org.wildfly.security.mechanism.oauth2,\
org.wildfly.security.mechanism.scram,\
org.wildfly.security.password,\
org.wildfly.security.password.impl,\
org.wildfly.security.password.interfaces,\
org.wildfly.security.password.spec,\
org.wildfly.security.password.util,\
org.wildfly.security.pem,\
org.wildfly.security.permission,\
org.wildfly.security.provider,\
org.wildfly.security.provider.util,\
org.wildfly.security.provider.util._private,\
org.wildfly.security.sasl,\
org.wildfly.security.sasl._private,\
org.wildfly.security.sasl.anonymous,\
org.wildfly.security.sasl.auth,\
org.wildfly.security.sasl.auth.util,\
org.wildfly.security.sasl.digest,\
org.wildfly.security.sasl.digest._private,\
org.wildfly.security.sasl.entity,\
org.wildfly.security.sasl.external,\
org.wildfly.security.sasl.gs2,\
org.wildfly.security.sasl.gssapi,\
org.wildfly.security.sasl.localuser,\
org.wildfly.security.sasl.oauth2,\
org.wildfly.security.sasl.otp,\
org.wildfly.security.sasl.plain,\
org.wildfly.security.sasl.scram,\
org.wildfly.security.sasl.util,\
org.wildfly.security.ssh,\
org.wildfly.security.ssh.util,\
org.wildfly.security.ssh.util._pivate,\
org.wildfly.security.ssl,\
org.wildfly.security.ssl._private,\
org.wildfly.security.tool,\
org.wildfly.security.tool.help,\
org.wildfly.security.util,\
org.wildfly.security.x500,\
org.wildfly.security.x500._private,\
org.wildfly.security.x500.cert,\
org.wildfly.security.x500.cert._private,\
org.wildfly.security.x500.cert.acme,\
org.wildfly.security.x500.cert.util,\
org.wildfly.security.x500.principal,\
org.wildfly.security.x500.util,\
org.wildfly.service,\
org.wildfly.service.capture,\
org.wildfly.service.descriptor,\
org.wildfly.subsystem,\
org.wildfly.subsystem.resource,\
org.wildfly.subsystem.resource.capability,\
org.wildfly.subsystem.resource.executor,\
org.wildfly.subsystem.resource.operation,\
org.wildfly.subsystem.service,\
org.wildfly.subsystem.service.capability,\
org.wildfly.subsystem.service.capture,\
org.wildfly.transaction,\
org.wildfly.transaction.client,\
org.wildfly.transaction.client._private,\
org.wildfly.transaction.client.naming,\
org.wildfly.transaction.client.naming.txn,\
org.wildfly.transaction.client.provider,\
org.wildfly.transaction.client.provider.jboss,\
org.wildfly.transaction.client.provider.remoting,\
org.wildfly.transaction.client.spi,\
org.wildfly.unstable,\
org.wildfly.unstable.api,\
org.wildfly.unstable.api.annotation,\
org.wildfly.unstable.api.annotation.classpath,\
org.wildfly.unstable.api.annotation.classpath.index,\
org.wildfly.unstable.api.annotation.classpath.runtime,\
org.wildfly.unstable.api.annotation.classpath.runtime.bytecode,\
org.xnio,\
org.xnio._private,\
org.xnio.channels,\
org.xnio.conduits,\
org.xnio.http,\
org.xnio.management,\
org.xnio.nio,\
org.xnio.sasl,\
org.xnio.ssl,\
org.xnio.streams,\
org.yaml,\
org.yaml.snakeyaml,\
org.yaml.snakeyaml.comments,\
org.yaml.snakeyaml.composer,\
org.yaml.snakeyaml.constructor,\
org.yaml.snakeyaml.emitter,\
org.yaml.snakeyaml.env,\
org.yaml.snakeyaml.error,\
org.yaml.snakeyaml.events,\
org.yaml.snakeyaml.extensions,\
org.yaml.snakeyaml.extensions.compactnotation,\
org.yaml.snakeyaml.external,\
org.yaml.snakeyaml.external.com,\
org.yaml.snakeyaml.external.com.google,\
org.yaml.snakeyaml.external.com.google.gdata,\
org.yaml.snakeyaml.external.com.google.gdata.util,\
org.yaml.snakeyaml.external.com.google.gdata.util.common,\
org.yaml.snakeyaml.external.com.google.gdata.util.common.base,\
org.yaml.snakeyaml.inspector,\
org.yaml.snakeyaml.internal,\
org.yaml.snakeyaml.introspector,\
org.yaml.snakeyaml.nodes,\
org.yaml.snakeyaml.parser,\
org.yaml.snakeyaml.reader,\
org.yaml.snakeyaml.representer,\
org.yaml.snakeyaml.resolver,\
org.yaml.snakeyaml.scanner,\
org.yaml.snakeyaml.serializer,\
org.yaml.snakeyaml.tokens,\
org.yaml.snakeyaml.util,\
proto.generated \
--initialize-at-run-time=org.jboss.as.server.services.net,\
io.smallrye.common.os.Process,\
io.undertow.server.protocol.ajp.AjpServerResponseConduit,\
io.undertow.server.protocol.ajp.AjpServerRequestConduit,\
io.undertow.server.handlers.resource.DirectoryUtils\\\$Blobs,\
org.jboss.msc.service.ServiceContainer\\\$Factory,\
org.wildfly.common.net,\
org.wildfly.httpclient.common.PoolAuthenticationContext,\
org.wildfly.httpclient.common.WildflyHttpContext,\
org.wildfly.httpclient.common.HttpContextGetterHolder,\
org.wildfly.httpclient.common.ConfigurationHttpContextSupplier,\
org.xnio.nio.WorkerThread,\
org.xnio.DefaultXnioWorkerHolder,\
org.xnio.channels.Channels,\
org.eclipse.jgit.util.FileUtils,\
org.eclipse.jgit.transport.HttpAuthMethod\\\$Digest,\
org.eclipse.jgit.internal.storage.file.WindowCache,\
org.eclipse.jgit.lib.RepositoryCache,\
org.eclipse.jgit.lib.internal.WorkQueue,\
org.jboss.remoting3.remote.RemoteConnection,\
io.smallrye.common.net.Inet,\
io.smallrye.common.net.CidrAddress,\
org.jboss.as.domain.http.server,\
org.jboss.remoting3.ConfigurationEndpointSupplier\\\$Holder,\
org.jboss.remoting3.ConnectionInfo,\
org.jboss.remoting3.remote.MessageReader,\
io.undertow.security.impl.SimpleNonceManager,\
org.jboss.classfilewriter.DefaultClassFactory,\
org.jboss.as.server.deployment.module.TempFileProviderService,\
org.jboss.as.server.DomainServerCommunicationServices,\
org.jboss.as.server.operations.NativeManagementServices \
--enable-url-protocols=jar,data \
--enable-sbom=false \
-H:ConfigurationFileDirectories=files \
--trace-object-instantiation=org.eclipse.jgit.util.FS_POSIX,java.beans.Introspector\\\$1,java.lang.Thread,org.wildfly.common.net.CidrAddressTable,org.xnio.nio.WorkerThread,java.net.Inet6Address,java.lang.ref.Cleaner,java.lang.ProcessHandleImpl,org.xnio.Buffers\\\$5,org.jboss.remoting3.ConnectionInfo\\\$EmptyIoFuture,java.net.Inet4Address,java.security.SecureRandom,java.util.Random,org.jboss.ejb.client.EJBClientContext,org.wildfly.security.auth.client.AuthenticationContext,org.wildfly.common.context.ContextManager,sun.nio.ch.FileChannelImpl,org.wildfly.httpclient.common.WildflyHttpContext,org.xnio.nio.NioXnioWorker,java.io.FilePermission,org.xnio.ByteBufferSlicePool,java.nio.DirectByteBuffer \
-cp ${current_dir}/min-core-server/jboss-modules.jar:wildfly-substitutions/target/wildfly-substitutions.jar"

for (( i=0; i<${arraylength}; i++ ));
do
  line=${array[$i]}":"
  if [[ $line =~ "org/jboss/logmanager/" ]]; then
    cmd="$cmd:$line"
  fi
  if [[ $line =~ "org/wildfly/common" ]]; then
    cmd="$cmd:$line"
  fi
  if [[ $line =~ "io/smallrye/common/cpu" ]]; then
    cmd="$cmd:$line"
  fi
  if [[ $line =~ "io/smallrye/common/net" ]]; then
    cmd="$cmd:$line"
  fi
if [[ $line =~ "io/smallrye/common/os" ]]; then
    cmd="$cmd:$line"
  fi
if [[ $line =~ "io/smallrye/common/expression" ]]; then
    cmd="$cmd:$line"
  fi
if [[ $line =~ "org/jboss/logging/" ]]; then
    cmd="$cmd:$line"
  fi
done

echo "$cmd" > "./build-image.sh"
chmod +x ./build-image.sh
./build-image.sh